### ISSUE TITLE
Training on Custom dataset

### ISSUE THREAD

**Issue by vibhavnirmal** [haotian-liu/yolact_edge#1]
Can I train this on custom coco datasets?

**Comment by haotian-liu** [comment]
Yes, and we will update the README soon for the instructions.

**Comment by vibhavnirmal** [comment]
Thank you so much.

**Comment by haotian-liu** [comment]
Updated documentation for custom dataset training: 2aa075cb6ae5282756a6bbe58e006c0ed31deee4, thanks.
