### ISSUE TITLE
Flow_base change

### ISSUE THREAD

**Issue by MiaoRain** [haotian-liu/yolact_edge#100]
Hi, haotian,  thanks for your work.  I have two questions:
1. if I just predict images rather than video, could I remove the "flow_base" setting in the Config, or how to change the "flow_base"?
2.  I download mobilenet weights "yolact_edge_mobilenetv2_54_800000.pth "  from Yolact and Yolact_edge link, separately, but seem very similar. How to run the Yolact model in yolact_edge? what parts of the Config and commands line should be changed?

Any suggestions would be appreciated.

**Comment by haotian-liu** [comment]
Hi, for your questions:

1. You can remove `flow_base`, but you should also check all of the conditional statements that is affected by `cfg.flow` and make sure they are handled correctly.
2. For the most up-to-date version of YolactEdge, you can use almost all of the Yolact models without doing any modifications, and YolactEdge code will convert it automatically.

**Comment by MiaoRain** [comment]
> Hi, for your questions:
> 
> 1. You can remove `flow_base`, but you should also check all of the conditional statements that is affected by `cfg.flow` and make sure they are handled correctly.
> 2. For the most up-to-date version of YolactEdge, you can use almost all of the Yolact models without doing any modifications, and YolactEdge code will convert it automatically.

Thanks a lot, haotian

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
