### ISSUE TITLE
How to make it with one trt engine?

### ISSUE THREAD

**Issue by sinuku** [haotian-liu/yolact_edge#102]
Hi!

Is there a reason for converting the trt engine by dividing it into multiple parts? (backbone, fpn_phase1, 2, lat_layer, proto_net)
If there is no specific reason, how can I make it with one engine?

Thank you!

**Environment:**
 - OS: Ubuntu 18.04
 - GPU: Jetson nano
 - CUDA Version : 10.2

**Comment by haotian-liu** [comment]
In order to get a balanced speed/accuracy trade off for INT8 conversion. Please refer to Section III A in our paper for detailed explanations.

**Comment by mechaadi** [comment]
Hi, is it possible to make it a single engine file?
