### ISSUE TITLE
The possibility of becoming a detector？

### ISSUE THREAD

**Issue by a-chance888** [haotian-liu/yolact_edge#104]
First of all, congratulations for completing such an excellent segmentation model. Now I want to use it only as a detector and use tensorrt to detect a single frame image. How should I do it? What do you think of this approach?

**Comment by haotian-liu** [comment]
You can start by setting `cfg.eval_mask_branch = False`. Some modifications might be needed as using it as the detector is not fully tested in YolactEdge.
