### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by hawk-z** [haotian-liu/yolact_edge#105]
jykj@jykj-SVE-2902VD-Invalid-entry-length-16-Fixed-up-to-11:~/anaconda3/envs/zqw/yolact_eage$ python eval.py --trained_model=weights/yolact_edge_vid_resnet50_847_50000.pth --score_threshold=0.3 --top_k=100 --video=vedio01.mp4:output_video01.mp4 --disable_tensorrt
Config not specified. Parsed yolact_edge_vid_resnet50_config from the file name.

2_dataset:None
tensorrt:True
[04/21 12:32:27 yolact.eval]: Loading model...
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'refine_convs' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
[04/21 12:32:31 yolact.eval]: Model loaded.
Traceback (most recent call last):
  File "eval.py", line 1421, in <module>
    evaluate(net, dataset)
  File "eval.py", line 892, in evaluate
    savevideo(net, inp, out)
  File "eval.py", line 820, in savevideo
    progress_bar = ProgressBar(30, num_frames)
  File "/home/jykj/anaconda3/envs/zqw/yolact_eage/utils/functions.py", line 56, in __init__
    self._update_str()
  File "/home/jykj/anaconda3/envs/zqw/yolact_eage/utils/functions.py", line 72, in _update_str
    num_bars = int(self.length * (self.cur_val / self.max_val))
ZeroDivisionError: division by zero

**Comment by haotian-liu** [comment]
It seems that your video is not loaded correctly, and open-cv does not read any frames. Please double check your video.
