### ISSUE TITLE
RuntimeError: nvrtc: error: invalid value for                    --gpu-architecture (-arch)  nvrtc compilation failed:

### ISSUE THREAD

**Issue by hawk-z** [haotian-liu/yolact_edge#107]
(zqw) jykj@jykj-SVE-2902VD-Invalid-entry-length-16-Fixed-up-to-11:~/anaconda3/envs/zqw/yolact_eage$ python eval.py --trained_model=weights/yolact_edge_vid_resnet50_847_50000.pth --score_threshold=0.3 --top_k=100 --video=data/vedio01.mp4:output_video01.mp4 --disable_tensorrt
Config not specified. Parsed yolact_edge_vid_resnet50_config from the file name.

2_dataset:None
tensorrt:True
[04/21 14:03:31 yolact.eval]: Loading model...
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/jykj/anaconda3/envs/zqw/lib/python3.7/site-packages/torch/jit/_recursive.py:182: UserWarning: 'refine_convs' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
[04/21 14:03:34 yolact.eval]: Model loaded.
num_priors:19248
index:tensor([ 0, 13, 16,  2,  7, 19, 17, 14, 35, 21, 10, 34, 26, 27, 32, 31,  5,  8,
        33, 28,  4, 20, 39, 23,  9, 18, 22,  1, 29, 24, 11,  3, 38, 30,  6, 15,
        12, 37, 25, 36])
classes:tensor([ 0, 13, 16,  2,  7, 19, 17, 14, 35, 21, 10, 34, 26, 27, 32, 31,  5,  8,
        33, 28,  4, 20, 39, 23,  9, 18, 22,  1, 29, 24, 11,  3, 38, 30,  6, 15,
        12, 37, 25, 36])
boxes:tensor([[-8.5627e-03,  2.1032e-02,  9.9750e-01,  9.9902e-01],
        [ 2.4334e-03,  4.7331e-02,  9.8136e-01,  9.9548e-01],
        [ 2.4334e-03,  4.7331e-02,  9.8136e-01,  9.9548e-01],
        [ 8.0498e-03,  2.0526e-02,  9.8390e-01,  1.0075e+00],
        [ 2.4334e-03,  4.7331e-02,  9.8136e-01,  9.9548e-01],
        [ 2.4334e-03,  4.7331e-02,  9.8136e-01,  9.9548e-01],
        [ 2.4334e-03,  4.7331e-02,  9.8136e-01,  9.9548e-01],
        [-8.5627e-03,  2.1032e-02,  9.9750e-01,  9.9902e-01],
        [ 2.4334e-03,  4.7331e-02,  9.8136e-01,  9.9548e-01],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 8.0498e-03,  2.0526e-02,  9.8390e-01,  1.0075e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 8.0498e-03,  2.0526e-02,  9.8390e-01,  1.0075e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 8.0498e-03,  2.0526e-02,  9.8390e-01,  1.0075e+00],
        [-8.5627e-03,  2.1032e-02,  9.9750e-01,  9.9902e-01],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 8.0498e-03,  2.0526e-02,  9.8390e-01,  1.0075e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00],
        [-8.5627e-03,  2.1032e-02,  9.9750e-01,  9.9902e-01],
        [ 1.8945e-04, -1.0732e-02,  9.9466e-01,  1.0127e+00]])
scores:tensor([6.7056e-02, 1.9588e-02, 8.5000e-03, 6.7640e-03, 6.1607e-03, 4.0106e-03,
        3.7381e-03, 3.7326e-03, 3.1213e-03, 2.3484e-03, 1.9944e-03, 1.6170e-03,
        1.5459e-03, 1.3592e-03, 1.2272e-03, 1.0904e-03, 1.0223e-03, 9.4915e-04,
        9.1639e-04, 8.9854e-04, 7.0229e-04, 5.5009e-04, 5.4835e-04, 5.2738e-04,
        4.7546e-04, 4.4341e-04, 4.3160e-04, 4.0417e-04, 3.8959e-04, 3.4685e-04,
        2.6738e-04, 2.3767e-04, 1.9760e-04, 1.9437e-04, 1.8155e-04, 1.7723e-04,
        1.7373e-04, 1.3914e-04, 7.2136e-05, 5.4294e-05])
Traceback (most recent call last):
  File "eval.py", line 1421, in <module>
    evaluate(net, dataset)
  File "eval.py", line 892, in evaluate
    savevideo(net, inp, out)
  File "eval.py", line 854, in savevideo
    processed = prep_display(preds, frame, None, None, undo_transform=False, class_color=True)
  File "eval.py", line 166, in prep_display
    score_threshold   = args.score_threshold)
  File "/home/jykj/anaconda3/envs/zqw/yolact_eage/layers/output_utils.py", line 117, in postprocess
    boxes[:, 1], boxes[:, 3] = sanitize_coordinates(boxes[:, 1], boxes[:, 3], b_h, cast=False)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void func_1(int v0, float* t1, float* t2, int v3, float* aten_clamp_flat, float* aten_clamp_flat_1) {
{
  if (512 * blockIdx.x + threadIdx.x<1 ? 1 : 0) {
    float v = __ldg(t2 + 0);
    float v_1 = __ldg(t1 + 0);
    float v_2 = __ldg(t2 + 0);
    float v_3 = __ldg(t1 + 0);
    aten_clamp_flat[512 * blockIdx.x + threadIdx.x] = (minimum(v,v_1)) - (float)(v0)<0.f ? 0.f : (minimum(v_2,v_3)) - (float)(v0);
    float v_4 = __ldg(t2 + 0);
    float v_5 = __ldg(t1 + 0);
    float v_6 = __ldg(t2 + 0);
    float v_7 = __ldg(t1 + 0);
    aten_clamp_flat_1[512 * blockIdx.x + threadIdx.x] = (maximum(v_4,v_5)) + (float)(v0)>(float)(v3) ? (float)(v3) : (maximum(v_6,v_7)) + (float)(v0);
  }
}
}

Segmentation fault (core dumped)

**Comment by haotian-liu** [comment]
What is your environment (GPU, PyTorch, OS, etc.)? It seems a PyTorch/CUDA related issue.

**Comment by hawk-z** [comment]
python:3.7
pytorch 1.7
cuda 11.0
cudnn 8.0.0
Ubuntu 16.04

**Comment by haotian-liu** [comment]
What's your GPU?

**Comment by hawk-z** [comment]
RTX 3090

**Comment by haotian-liu** [comment]
Maybe try updaing to PyTorch 1.7.1: https://github.com/pytorch/pytorch/pull/48151.

**Comment by hawk-z** [comment]
I run in a virtual environment. Does this have an impact

**Comment by haotian-liu** [comment]
Maybe try updaing to PyTorch 1.7.1? There seems to be a bug with RTX 30 series for PyTorch 1.7: https://github.com/pytorch/pytorch/pull/48151.

**Comment by haotian-liu** [comment]
What do you mean by virtual environment? Docker?

**Comment by hawk-z** [comment]
conda

**Comment by haotian-liu** [comment]
It is very unlikely, as I am also using conda. It seems to be a PyTorch error. All I could think of with the information you provided is the PyTorch version as indicated in https://github.com/pytorch/pytorch/issues/47658 and https://github.com/pytorch/pytorch/pull/48151.

**Comment by ArtificialNotImbecile** [comment]
Pytorch 1.8.1 also has exactly the same  issue(1.7.1 works fine)
