### ISSUE TITLE
700x700px or other image size formats?

### ISSUE THREAD

**Issue by ngeerlingsriwo** [haotian-liu/yolact_edge#110]
Is it possible to use 700x700 or another size format instead of the 550x550 px, as in Yolact? If so, do you only need to change the 'max_size' parameter in data/config.py or is there more to it? 
I would like to evaluate images of 1280x720px and cannot achieve enough mask accuracy for thin (10px wide) objects.

**Comment by haotian-liu** [comment]
`input_sizes` of TensorRT modules should also be changed if you are going to use TensorRT. An automatic configuration in this will be updated later.

**Comment by ngeerlingsriwo** [comment]
Thank you!

**Comment by ngeerlingsriwo** [comment]
Do I only need to change the values 69 in 'input_sizes', or also the other values? If I only change 69 to 90 (for a 720x720 image) the code runs, even though I did not change the other values. Before I start training for a few days I'd like to make sure that my settings are correct.

**Comment by haotian-liu** [comment]
It does not affect the training -- and only affect when you enable TensorRT conversion. Thus not only "69"s need to be modified, but also other number for corresponding feature map needs to be adjusted as well.

**Comment by kostromins** [comment]
Hi!

We are also aiming to use a different max_size value because of small objects.

**Comment by haotian-liu** [comment]
@kostromins If a different `max_size` is used, `input_size` for tensorrt conversion modules needs to be changed to accomodate for the change. Thanks!

**Comment by marvision-ai** [comment]
@haotian-liu  , what was the formula you used to provide the proper numbers in the input_sizes=[....] for your custom width x height?
I am struggling with this issue for a custom 1080x720 model. 

Thank you!
