### ISSUE TITLE
Different small problems. 

### ISSUE THREAD

**Issue by FPSychotic** [haotian-liu/yolact_edge#111]
I got running this in real time from video-camera in a Jetson Xavier NX  but I'm absolutely  beginner and for sure I'm absolutely amazed, so first congratulations and thanks by share knowledge and effort.

i have the next problems that maybe are not issues ,but there is not a conversation room to ask other users. 

-I  need use sudo and python3 command, in the guide don't use sudo,  how I an fix that (need use  python3 I guess is not a problem but correct the guide would be nice)?  Maybe giving permissions to some folder or making rules? (I don't know how do it if it is needed sadly)  
- It takes the 90% of my ram, and it doesn't use the  swap available (8gb), how I could low the resolution to low the memory usage? would help use the swap before use the whole memory? how, swappiness?
- Im using always this command to run it :

`sudo python3 eval.py --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size 2 --video=0 --use_tensorrt_safe_mode` 

so it needs convert to TRT every time, can I save and reuse the converted model, if so, what command I need use and were is the file? .

-the guide's file names of download with the command doesn't fit, so the guide wont work, but the mirror's ones are right and will work following the guide, for someone like me that is difficult to note.

Any help from any user will help, Im quite lost
cheers

**Comment by haotian-liu** [comment]
For your questions,
 - need sudo: you need to add your user to `video` group so as to use the graphics card.
 - ram usage: see #88, and you can try use fp16 conversion also (which do not require calibration). And the model caches TensorRT modules, and it will automatically load the cached TRT models without converting if it is available.
 - guide download: I am not quite sure about what you mean by guide and mirror, please elaborate.

**Comment by FPSychotic** [comment]
Ohh, thanks by the help I will try all that!

The guide issue is when you click download the weights, the filename do not fit with the name in the command included in the instalation guide (as it include the mobilenet word). But if you click to download from the mirror link, the file name that is downloaded fits (it doesn't include mobilenet in the name) with the one in the guide.

My English is very bad I hope I could explain it properly this time
