### ISSUE TITLE
Error opencv/gstreamer after last pull up and resizing input video advice.

### ISSUE THREAD

**Issue by FPSychotic** [haotian-liu/yolact_edge#116]
Hi yesterday there was a pull up or modification, I dont remember I had this error previous to it. It will appear always.
Xavier NX, USB 720p webcam model Microsoft HD-6000

`[ WARN:0] global /tmp/build_opencv/opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1`

Also I found what could be a possible bug, setting `--video_multiframe=2 --trt_batch_size=2` it will takes the full 7.8gb of ram always, converting and running, everytime you running it. 
If I set `--video_multiframe=1 --trt_batch_size=1` it will take only 5.7-6Gb of ram.Same frame rate and performance.
after this if I run    `setting --video_multiframe=2 --trt_batch_size=2` again, from that moment it always will use 6Gb, instead 7.9Gb as before, and always will use 6Gb from then. Bg or not I hope this will help to someone with this issue.

Also I would ask you how I could resize the input image to fit aprox. the processing resolution, in example 640x480 instead 720p Im getting.
I read (if I understood right) you will add resize the inference conversion output , that is great, thank you I would love can low resolutions in input and output

My problem with sudo continued after added the user to video group, probably it is due I installed something wrong or using y python system instead a environment .env . It is not a issue from your part but maybe affect to the described above.
Cheers

**Comment by haotian-liu** [comment]
You can resize the image before feeding into the network: even if the model resizes the images to 550, this will still save some memory and increase speed as in the drawing process, the image/masks will be resized back to the original resolution.
