### ISSUE TITLE
running error~

### ISSUE THREAD

**Issue by A-good-kids** [haotian-liu/yolact_edge#117]
**Describe the bug**
![2021-05-10 14-05-43屏幕截图](https://user-images.githubusercontent.com/65146982/117613379-66ef3f00-b199-11eb-9dfd-6ddf3ef20a35.png)

**To Reproduce**
python eval.py --trained_model=weights/yolact_edge_pascal_499_5000.pth --score_threshold=0.3 --top_k=100 --image=9.jpg --disable_tensorrt 

l set cfg.eval_mask_branch = False ,just want it as a detector!

**Environment:**
 - OS: Ubuntu 18.04]
 - GPU: 1660
 - CUDA Version 10.2

what should i do to solve the problem!    if you can provide some advices that will be very helpful for me !   Thank you very much!

**Comment by haotian-liu** [comment]
Currently using as the object detector is not fully supported, and you might need to modfiy the code a little bit. Thanks.
