### ISSUE TITLE
Cannot convert model train on custom data to tensorRT while the pretrained model can

### ISSUE THREAD

**Issue by letuantang** [haotian-liu/yolact_edge#119]
Hi Haotian-liu. Thank you for the great job that has been done by you and your team.
We are looking for an instance segmentation network that can be run on the Jetson nano. Fortunately, this repo release at the right time for us. We are trying to duplicate your work with our custom data on Jetson nano (not Jetson AGX Xavier).
We are successful can train the network on our custom dataset and can successfully do the inference mode without tensorRT (2.25 to 2.5 s/frame). This speed is still far away from our expectations. If the inference time is around 0.5 to 0.8s/frame then it can meet our minimum requirement. 
I follow your instruction before train the network on the custom dataset:

my_custom_dataset = dataset_base.copy({
    'name': 'My Dataset',

    'train_images': 'path_to_training_images',
    'train_info':   'path_to_training_annotation',

    'valid_images': 'path_to_validation_images',
    'valid_info':   'path_to_validation_annotation',

    'has_gt': True,
    'class_names': ('my_class_id_1', 'my_class_id_2', 'my_class_id_3', .., my_class_id_10), #ten classes
})

In yolact_edge_config in the same file, change the value for 'dataset' to 'my_custom_dataset' and add 'num_classes' = 11

The resolution of my images is 640x480 then I modified "max_size = 640"

I started the training and everything is good, the model is converged actually. 

I follow the instruction to convert model to use the tensorRT then it failed at the step convert backbone to tensorRT even in case I have increase the swap equal to 16GB. One more things make me confused and cannot explain is that when I try to convert 
"yolact_edge_54_800000.pth" which used as the my pretrained model (downloaded for your Github (R-101-FPN)) then it is ok after 3 hours of converting. 
I attached here the proof for the converting process:
1. yolact_edge_54_800000.pth is OK to convert to use TensorRT
![z2483079997700_d02dd1140caf0d9ba2927c166c01cc58](https://user-images.githubusercontent.com/32661645/117897810-be9ebf00-b2ed-11eb-8225-abda743b8fec.jpg)
2. New model on custom dataset failed to convert to use TensorRT
![z2483079988698_3e411b9cd5b13c029b9dfa285a0393e6](https://user-images.githubusercontent.com/32661645/117897834-cd857180-b2ed-11eb-9195-5b0fdb41d402.jpg)
Hope you can give me some hints to solve it. Is it because the performance of Jetson nano is too weak?
P/S: if I comment on these lines to convert backbone to tensorRT and keep the rest (protonet, fpn phase 1&2, Prediction) as normal then they are successfully be converted.

**Comment by haotian-liu** [comment]
Please try reducing the calibration set: #101

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
