### ISSUE TITLE
Where to find sub-training split and sub-validation split for YouTube-VIS dataset?

### ISSUE THREAD

**Issue by LiYingwei** [haotian-liu/yolact_edge#12]
I assume there should be a video list to indicate whether a video is for training or for validation?

**Comment by haotian-liu** [comment]
For the sake of compatibility, we generated the video list and its corresponding annotation files. Download [here](https://github.com/haotian-liu/yolact_edge/blame/master/INSTALL.md#L48)

**Comment by LiYingwei** [comment]
Thanks for your quick response!
