### ISSUE TITLE
是否使用tensorRT加速预测时，在单张图片的预测速度没有变化

### ISSUE THREAD

**Issue by simplew2011** [haotian-liu/yolact_edge#121]
训练好一个单类别模型：
       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box | 82.19 | 97.19 | 96.10 | 96.07 | 94.12 | 93.05 | 91.57 | 86.46 | 79.77 | 64.00 | 23.59 |
  mask | 83.39 | 96.10 | 96.08 | 94.96 | 94.87 | 93.86 | 91.86 | 89.28 | 81.07 | 65.59 | 30.24 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
使用预测脚本：

**关闭TensorRT:**
appuser@af195f4772c7:/yolact_edge$ python eval.py --trained_model=weights/yolact_base_1707_210000.pth --score_threshold=0.2 --top_k=1 --images=datasets/white/JPEGImages-output --config=yolact_edge_config --disable_tensorrt
[05/21 08:09:51 yolact.eval]: Loading model...
[05/21 08:09:53 yolact.eval]: Model loaded.

============= 0.9803211688995361
datasets/white/JPEGImages/shuangse_7_409_3229_0_640_640_0_0.jpg -> output/shuangse_7_409_3229_0_640_640_0_0.png
============= 0.22702407836914062
datasets/white/JPEGImages/shuangse_307_214_1280_0_640_640_0_0.jpg -> output/shuangse_307_214_1280_0_640_640_0_0.png
============= 0.022992849349975586
datasets/white/JPEGImages/shuangse_430_347_640_0_640_640_0_0.jpg -> output/shuangse_430_347_640_0_640_640_0_0.png
============= 0.023056745529174805
datasets/white/JPEGImages/shuangse_284_189_640_0_640_640_0_0.jpg -> output/shuangse_284_189_640_0_640_640_0_0.png
============= 0.022995710372924805
datasets/white/JPEGImages/shuangse_208_110_1280_0_640_640_0_0.jpg -> output/shuangse_208_110_1280_0_640_640_0_0.png
============= 0.023023366928100586
datasets/white/JPEGImages/shuangse_229_133_2560_0_640_640_0_0.jpg -> output/shuangse_229_133_2560_0_640_640_0_0.png
============= 0.023021936416625977
datasets/white/JPEGImages/shuangse_332_241_640_0_640_640_0_0.jpg -> output/shuangse_332_241_640_0_640_640_0_0.png
============= 0.022957563400268555
datasets/white/JPEGImages/shuangse_41_324_640_0_640_640_0_0.jpg -> output/shuangse_41_324_640_0_640_640_0_0.png
============= 0.022847414016723633
datasets/white/JPEGImages/shuangse_419_334_0_0_640_640_0_0.jpg -> output/shuangse_419_334_0_0_640_640_0_0.png
============= 0.02286839485168457
datasets/white/JPEGImages/shuangse_269_176_0_0_640_640_0_0.jpg -> output/shuangse_269_176_0_0_640_640_0_0.png
============= 0.022897720336914062
datasets/white/JPEGImages/shuangse_229_133_1280_0_640_640_0_0.jpg -> output/shuangse_229_133_1280_0_640_640_0_0.png

**使用TensorRT:**
appuser@af195f4772c7:/yolact_edge$ python eval.py --trained_model=weights/yolact_base_1707_210000.pth --score_threshold=0.2 --top_k=1 --use_fp16_tensorrt --images=datasets/white/JPEGImages-output --config=yolact_edge_config --benchmark
[05/21 08:10:37 yolact.eval]: Loading model...
[05/21 08:10:39 yolact.eval]: Model loaded.
[05/21 08:10:39 yolact.eval]: Converting to TensorRT...
[05/21 08:10:39 yolact.eval]: Converting backbone to TensorRT...
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[05/21 08:10:41 yolact.eval]: Converting protonet to TensorRT...
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[05/21 08:10:41 yolact.eval]: Converting FPN to TensorRT...
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.5
[05/21 08:10:41 yolact.eval]: Converting PredictionModule to TensorRT...
[05/21 08:10:47 yolact.eval]: Converted to TensorRT.

============= 0.04282426834106445
datasets/white/JPEGImages/shuangse_7_409_3229_0_640_640_0_0.jpg -> output/shuangse_7_409_3229_0_640_640_0_0.png
============= 0.11768555641174316
datasets/white/JPEGImages/shuangse_307_214_1280_0_640_640_0_0.jpg -> output/shuangse_307_214_1280_0_640_640_0_0.png
============= 0.029256105422973633
datasets/white/JPEGImages/shuangse_430_347_640_0_640_640_0_0.jpg -> output/shuangse_430_347_640_0_640_640_0_0.png
============= 0.029204368591308594
datasets/white/JPEGImages/shuangse_284_189_640_0_640_640_0_0.jpg -> output/shuangse_284_189_640_0_640_640_0_0.png
============= 0.029629945755004883
datasets/white/JPEGImages/shuangse_208_110_1280_0_640_640_0_0.jpg -> output/shuangse_208_110_1280_0_640_640_0_0.png
============= 0.029097557067871094
datasets/white/JPEGImages/shuangse_229_133_2560_0_640_640_0_0.jpg -> output/shuangse_229_133_2560_0_640_640_0_0.png
============= 0.029277563095092773
datasets/white/JPEGImages/shuangse_332_241_640_0_640_640_0_0.jpg -> output/shuangse_332_241_640_0_640_640_0_0.png
============= 0.027858257293701172
datasets/white/JPEGImages/shuangse_41_324_640_0_640_640_0_0.jpg -> output/shuangse_41_324_640_0_640_640_0_0.png
============= 0.027270078659057617
datasets/white/JPEGImages/shuangse_419_334_0_0_640_640_0_0.jpg -> output/shuangse_419_334_0_0_640_640_0_0.png
============= 0.027046918869018555
datasets/white/JPEGImages/shuangse_269_176_0_0_640_640_0_0.jpg -> output/shuangse_269_176_0_0_640_640_0_0.png
============= 0.026633739471435547
datasets/white/JPEGImages/shuangse_229_133_1280_0_640_640_0_0.jpg -> output/shuangse_229_133_1280_0_640_640_0_0.png
============= 0.026652097702026367
datasets/white/JPEGImages/shuangse_237_142_1280_0_640_640_0_0.jpg -> output/shuangse_237_142_1280_0_640_640_0_0.png

发现开启TensorRT耗时没缩减，反而增加了（0.023  ---->   0.026）

**Comment by simplew2011** [comment]
把模型和配置文件及测试图像上传了。

您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/64a958d42ab64e 或进入 cowtransfer.com 获取，在首页输入取件码：425967（24小时内有效）

**Comment by haotian-liu** [comment]
This is somewhat expected: processing first several images requires putting networks on the GPU and there are other mechanisms happening in the background. You could measure the speed by processing the image multiple times and see the difference.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
