### ISSUE TITLE
Great project， but the memory usage is too big.

### ISSUE THREAD

**Issue by Byronnar** [haotian-liu/yolact_edge#124]
**Describe the bug**
hen I do inference with tensorrt(torch2trt), the memory need 3.5G(not calibration), it's too big for me, could you tell me how to reduce the memory usage? Thank you!

**To Reproduce**
Just run acoording to README;

**Expected behavior**
Reduce the 

**Full logs**
If applicable, add full logs to help explain your problem.

**Environment:**
 - OS: [Ubuntu 18.04]
 - GPU: [Jetson Xavier NX]
 - CUDA Version [10.2]

**Additional context**

**Comment by Byronnar** [comment]
My mistakes

**Comment by Byronnar** [comment]
Loking for your reply! Thank you!

**Comment by Byronnar** [comment]
@haotian-liu

**Comment by haotian-liu** [comment]
Hi, you could try reducing the calibration image dataset, reduce the image size, or use the FP16 only (which does not require calibration).

**Comment by Byronnar** [comment]
> Hi, you could try reducing the calibration image dataset, reduce the image size, or use the FP16 only (which does not require calibration).

Thanks for your reply! I have reduced the calibration image dataset is not work,  the FP16 only mode also need 3.5G, if reduce the image size, it will reduce the performence;

**Comment by haotian-liu** [comment]
Maybe you can try to convert each module to TensorRT separately, load the converted module later and run. This might require some extra code modification on your side. Thanks!

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
