### ISSUE TITLE
AP per category

### ISSUE THREAD

**Issue by mona0809** [haotian-liu/yolact_edge#125]
Thanks for sharing your implementation. Due to your well written readme, I was able to train YolactEdge on my own dataset. How do I get the average precision per category?

**Comment by haotian-liu** [comment]
In `calc_map` function (in `eval.py`), you can see that the ap_data is organized in this way: `ap_data[iou_type][iou_idx][_class]`, thus you can modify the `calc_map` function to output the per-class mAP. Hope this helps, thanks.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
