### ISSUE TITLE
RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

### ISSUE THREAD

**Issue by Yang-Changhui** [haotian-liu/yolact_edge#127]
hi,when I detect an image,there is a error.The error is :RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4,
I hope one can help me.
Thanks !

**Comment by haotian-liu** [comment]
Please try [this](https://github.com/haotian-liu/yolact_edge#handling-inference-error-when-using-tensorrt) or refer to #126 and other related issues, thanks!

**Comment by Yang-Changhui** [comment]
ok.Thanks very much.
But,my detect processing FPS is only 5.33 and how to impove it

**Comment by haotian-liu** [comment]
Please specify the system configuration, and the backbone / TensorRT config you are using.

**Comment by Yang-Changhui** [comment]
My tensorrt version is 6.0.1.10,is this the reason?

**Comment by haotian-liu** [comment]
Please specify the system configuration (CPU/GPU/Platform), and the backbone (R50/R101/...) / TensorRT (FP16/INT8) config you are using.

**Comment by Yang-Changhui** [comment]
GPU,jetson agx xavier,R-101-FPN,FP16
commend:python3 eval.py --trained_model=yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size 2 --video=0 --use_fp16_tensorrt

**Comment by haotian-liu** [comment]
For FPS of video processing, it includes mask drawing and the speed is also related to video frame size (e.g. FPS of 1080p video is lower than 720p videos). Also, FP16 is slower than INT8 conversion. If the video size is similar to 550x550, then please first verify that everything is fine with the `--benchmark` command.

**Comment by Yang-Changhui** [comment]
Fine.Thanks!

**Comment by haotian-liu** [comment]
Thanks, hope it helps!

**Comment by Yang-Changhui** [comment]
hi,when I set --use_fp16_tensorrt=True，the program runs normally.When the --use_fp16_tensorrt is False,there is a error.
RuntimeError: stack expects a non-empty TensorList

**Comment by haotian-liu** [comment]
Please refer to [INSTALL.MD](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md) for calibration dataset.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
