### ISSUE TITLE
how can i train with a low resolution?

### ISSUE THREAD

**Issue by yjt9299** [haotian-liu/yolact_edge#129]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (full command you are using).

**Expected behavior**

**Full logs**
If applicable, add full logs to help explain your problem.

**Environment:**
 - OS: [e.g. Ubuntu 18.04]
 - GPU: [e.g. RTX 2080 Ti *4]
 - CUDA Version [e.g. 10.2]

**Additional context**

**Comment by yjt9299** [comment]
any params should i update if i want to trian the yolact_edge with resolution of 224*224?

**Comment by haotian-liu** [comment]
Please refer to #110, thanks.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
