### ISSUE TITLE
The difference between using and not using --benchmark

### ISSUE THREAD

**Issue by njuxx** [haotian-liu/yolact_edge#130]
Hi,
what's the difference if I set the argument `--benchmark' compared to not set that?

**Comment by haotian-liu** [comment]
When using `--benchmark`, the code will turn on all CUDNN optimization flags, not drawing the masks over the image, and measure the FPS of the code.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
