### ISSUE TITLE
Error evaluating "python3 eval.py ...."

### ISSUE THREAD

**Issue by 1seck** [haotian-liu/yolact_edge#138]
> **Describe the bug**
Seems like `eval.py` is looking for a Python-module named YoutubeVISEval or alike, or I dont understand the python code :)
> Traceback (most recent call last):
>   File "eval.py", line 1280, in <module>
>     evaluate(net, dataset)
>   File "eval.py", line 981, in evaluate
>     from data.youtube_vis import YoutubeVISEval, collate_fn_youtube_vis_eval
> ModuleNotFoundError: No module named 'data.youtube_vis'

**To Reproduce**
Following steps for evaluating YoutubeVIS then running:
`python3 eval.py --trained_model=./weights/yolact_edge_vid_847_50000.pth
`
**Expected behavior**
Normal python script behavior, no errors.

**Full logs**

> ubuntu@*****:~/yolact_edge$ python3 eval.py --trained_model=./weights/yolact_edge_vid_847_50000.pth
> Config not specified. Parsed yolact_edge_vid_config from the file name.
> 
> [08/18 11:58:22 yolact.dataset]: Loading annotations into memory...
> [08/18 11:58:25 yolact.dataset]: 334 videos loaded in 2.77s.
> [08/18 11:58:25 yolact.eval]: Loading model...
> [08/18 11:58:30 yolact.eval]: Model loaded.
> [08/18 11:58:30 yolact.eval]: Converting to TensorRT...
> [08/18 11:58:30 yolact.eval]: Converting backbone to TensorRT...
> [08/18 11:58:33 yolact.eval]: Converting protonet to TensorRT...
> [08/18 11:58:34 yolact.eval]: Converting FPN to TensorRT...
> [08/18 11:58:34 yolact.eval]: Converting PredictionModule to TensorRT...
> [08/18 11:58:48 yolact.eval]: Converting SPA to TensorRT...
> [08/18 11:58:48 yolact.eval]: Converting flow_net to TensorRT...
> [08/18 11:58:48 yolact.eval]: Converted to TensorRT.
> 
> Traceback (most recent call last):
>   File "eval.py", line 1280, in <module>
>     evaluate(net, dataset)
>   File "eval.py", line 981, in evaluate
>     from data.youtube_vis import YoutubeVISEval, collate_fn_youtube_vis_eval
> ModuleNotFoundError: No module named 'data.youtube_vis'
> 

**Environment:**
AGX 
ii  nvidia-container-csv-cuda                  10.2.89-1                                        arm64        Jetpack CUDA CSV file
ii  nvidia-container-csv-cudnn                 8.0.0.180-1+cuda10.2                             arm64        Jetpack CUDNN CSV file
ii  nvidia-container-csv-tensorrt              7.1.3.0-1+cuda10.2                               arm64        Jetpack TensorRT CSV file
ii  nvidia-container-csv-visionworks           1.6.0.501                                        arm64        Jetpack VisionWorks CSV file

 - OS:  Ubuntu 18.04, 4.9.201-tegra
 - GPU: AGX...

**Comment by 1309123499** [comment]
would you please tell me how do you get the YoutubeVIS valid files? i can only find the valid.v4.json.
