### ISSUE TITLE
No improvement in FPS after using TensorRT

### ISSUE THREAD

**Issue by rgkannan676** [haotian-liu/yolact_edge#140]
Hi,

I was trying to check the FPS using the evaluate.py. I got almost similar or little less performance when using TensorRT compared to not using. 

I am using FP16 instead of INT8.

### FP16-only TensorRT
----------------------------

```
python3 eval.py --use_fp16_tensorrt --trained_model=yolact_edge_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=40 --trt_batch_size 42 --video=dog.mp4

Config not specified. Parsed yolact_edge_resnet50_config from the file name.

[08/19 10:46:39 yolact.eval]: Loading model...
[08/19 10:46:41 yolact.eval]: Model loaded.
[08/19 10:46:41 yolact.eval]: Converting to TensorRT...
[08/19 10:46:41 yolact.eval]: Converting backbone to TensorRT...
[08/19 10:46:41 yolact.eval]: Converting protonet to TensorRT...
[08/19 10:46:41 yolact.eval]: Converting FPN to TensorRT...
[08/19 10:46:41 yolact.eval]: Converting PredictionModule to TensorRT...
[08/19 10:46:53 yolact.eval]: Converted to TensorRT.

Done.
Number of threads: 4


Processing FPS: 40.08 | Video Playback FPS: 0.00 | Frames in Buffer: 0 
Processing FPS: 39.40 | Video Playback FPS: 0.00 | Frames in Buffer: 0 
Processing FPS: 37.99 | Video Playback FPS: 0.00 | Frames in Buffer: 39 
Processing FPS: 34.37 | Video Playback FPS: 15.33 | Frames in Buffer: 53    
Processing FPS: 32.30 | Video Playback FPS: 18.53 | Frames in Buffer: 58    
Processing FPS: 31.17 | Video Playback FPS: 20.39 | Frames in Buffer: 60 

```

### FP16 without TensorRT
------------------------------------

```
python3 eval.py --use_fp16_tensorrt --disable_tensorrt --trained_model=yolact_edge_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=40 --trt_batch_size 42 --video=dog.mp4

Config not specified. Parsed yolact_edge_resnet50_config from the file name.

[08/19 10:48:35 yolact.eval]: Loading model...
[08/19 10:48:36 yolact.eval]: Model loaded.
/home/user/.local/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)

Done.
Number of threads: 4


Processing FPS: 39.61 | Video Playback FPS: 0.00 | Frames in Buffer: 0 
Processing FPS: 39.11 | Video Playback FPS: 0.00 | Frames in Buffer: 0 
Processing FPS: 38.77 | Video Playback FPS: 15.49 | Frames in Buffer: 32    
Processing FPS: 37.95 | Video Playback FPS: 15.22 | Frames in Buffer: 55    
Processing FPS: 37.22 | Video Playback FPS: 16.15 | Frames in Buffer: 74    
Processing FPS: 36.05 | Video Playback FPS: 19.22 | Frames in Buffer: 80    

```

The image vector dimension is torch.Size([40, 3, 550, 550]) for both cases.

OS: ubuntu 18.04
cuda - cuda-10.2
gpu: geforce 1080 ti
TensorRT: TensorRT 7.1.3.4 for Ubuntu 18.04 and CUDA 10.2 TAR package

Can you advise what can be the issue here?

**Comment by rgkannan676** [comment]
Hi @haotian-liu please advise what changes I need to do to increase the FPS near to 100 as mentioned in the performance [tables](https://github.com/haotian-liu/yolact_edge). Thanks.

**Comment by haotian-liu** [comment]
@rgkannan676 Please try first using `--benchmark` to see what the FPS is for both with and without TensorRT.

**Comment by MiaoRain** [comment]
> @rgkannan676 Please try first using `--benchmark` to see what the FPS is for both with and without TensorRT.

BTW, haotian, what's difference by using or not using "--benchmark"

**Comment by haotian-liu** [comment]
@MiaoRain `--benchmark` is currently used to measure the inference speed on COCO/YouTubeVIS dataset, with all optimization flags turned on.

**Comment by rgkannan676** [comment]
@haotian-liu Thank you for the reply. Unfortunately I don't have access to gpu: geforce 1080 ti now. I tested in gpu: geforce 2080 ti and was able to attain the FPS mentioned in the paper. 

I will update once I can access the geforce 1080 ti.

**Comment by LMR2018** [comment]
> 嗨@haotian-liu请告知我需要做哪些更改才能将 FPS 提高到接近 100，如性能[表中所述](https://github.com/haotian-liu/yolact_edge)。谢谢。
Can you make the model run more than 100FPS? I'm still at 8FPS

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
