### ISSUE TITLE
Imagenet-pretrained  Resnet50 model .pth file is in tar format instead of binary

### ISSUE THREAD

**Issue by rgkannan676** [haotian-liu/yolact_edge#141]
Hi @haotian-liu ,

I was trying to download the image-net pre-trained resnet50 model for training from the link given in the page.

##### For Resnet50, download resnet50-19c8e357.pth from [here](https://drive.google.com/file/d/1Jy3yCdbatgXa5YYIdTCRrSV0S9V5g1rn/view?usp=sharing).

The link points to a .zip file instead of .pth. Can you please provide the .pth file for the same.

Thanks.

**Comment by haotian-liu** [comment]
It is a `.pth` file.

**Comment by rgkannan676** [comment]
@haotian-liu . Thank you for the reply. 

When  'resnet50-19c8e357.pth' is downloaded, I get a tar archive file with name  'resnet50-19c8e357.pth' with following files inside
- pickle
- storages
- sys_info
- tensors

But for 101 and mobile-net it's a .pth binary file.

**Comment by haotian-liu** [comment]
You can simply rename it to `.pth` and it shall work.

**Comment by rgkannan676** [comment]
@haotian-liu Thank you for the help. It worked.
