### ISSUE TITLE
Using provided Dockerfile with Jetson AGX Xavier

### ISSUE THREAD

**Issue by johnfmoran2** [haotian-liu/yolact_edge#143]
Hi, I am trying to use the Dockerfile with a Jetson AGX Xavier.   It is pulling the amd64 image from  nvcr.io instead of the desired arm64.  Running the build command as specified in the instructions results is:

[Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

so I attempted to modify the build command to include the platform flag as follows:

docker build --platform=linux/arm64 --build-arg USER_ID=$UID -t yolact_edge_image .

and that resulted in this error:

WARNING: Pulled image with specified platform (linux/arm64), but the resulting image's configured platform (linux/amd64) does not match.
This is most likely caused by a bug in the build system that created the fetched image (nvcr.io/nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04).
Please notify the image author to correct the configuration.

Any advice?  Thanks!

**Comment by akaneko1019** [comment]
I don't think the Dockerfile in this repository can be used with Jetson. You need to use "L4T Base" as the Base Image.
