### ISSUE TITLE
running error,please!

### ISSUE THREAD

**Issue by a-chance888** [haotian-liu/yolact_edge#15]
File "eval.py", line 2, in <module>
    from yolact import Yolact
  File "/path/to/clone/yolact_edge/yolact.py", line 4, in <module>
    from torchvision.models.resnet import Bottleneck, conv1x1, conv3x3
ImportError: cannot import name 'conv1x1'

**Comment by haotian-liu** [comment]
Please verify that `torchvision` is installed correctly. For more details for environment configuration, please refer to [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md).
