### ISSUE TITLE
Demo eval possible without downloading json?

### ISSUE THREAD

**Issue by R4ZZ3** [haotian-liu/yolact_edge#16]
Hi,

I want to try out the this option using my webcam:
# Display a webcam feed in real-time. If you have multiple webcams pass the index of the webcam you want instead of 0.
python eval.py --coco_transfer --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --video=0

Do I really need to download the 21GB json to support testing the model? Could you make example to just run it without calibration?

![image](https://user-images.githubusercontent.com/25264037/103348708-7d76e280-4aa3-11eb-98ab-c9cac148a0dc.png)

**Comment by haotian-liu** [comment]
It is possible to calibrate without JSON file, and we are working on the implementation for that (with a general calibration option). Right now, we can evaluate either without TensorRT optimization or without INT8 calibration (with FP16-only TensorRT optimization). Please refer to [here](https://github.com/haotian-liu/yolact_edge/blame/a08cf222ee917498f5ffc2b4a5f243c377993889/README.md#L82).

**Comment by R4ZZ3** [comment]
I will look into it maybe tomorrow, thanks 👍

**Comment by R4ZZ3** [comment]
It works, thanks!

![image](https://user-images.githubusercontent.com/25264037/103410413-c8602b00-4b73-11eb-9121-4e931c59304c.png)

**Comment by xjsxujingsong** [comment]
@R4ZZ3  How can you make it work in Windows OS? I followed the installation steps but ignored Tensorrr part. 
It gave pytorch error: 

  File "D:\code\yolact_edge\layers\functions\__init__.py", line 1, in <module>
    from .detection import Detect
  File "D:\code\yolact_edge\layers\functions\detection.py", line 13, in <module>
    if dist.is_initialized():
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

**Comment by R4ZZ3** [comment]
replace dist.initialized() with dist.is_available()

in detection.py (layers/functions/detection.py):

`import pyximport
pyximport.install(setup_args={"include_dirs":np.get_include()}, reload_support=True)
if dist.**is_available():**
    dist.barrier()
from utils.cython_nms import nms as cnms`

**Comment by xjsxujingsong** [comment]
@R4ZZ3  Thank you very much. It's working now.

**Comment by cyrilzakka** [comment]
I tried running the `!python3 eval.py --config yolact_edge_pytorch_config --coco_transfer --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --video=video.mp4` command but I get the following error `yolact_edge_pytorch_config' is not defined`
