### ISSUE TITLE
I would like to know the same training method as the YolactEdge paper(ICRA 2021).

### ISSUE THREAD

**Issue by JunsukLee** [haotian-liu/yolact_edge#166]
If I follow the 4 commands below in order, will I get the same result as your paper?
I want to train on my computer and get the same results from your paper.

//Trains using the base edge config with a batch size of 8 (the default).
//Training resnet101_reducedfc.pth
python train.py --config=yolact_edge_config

//Pre-train the image based model
//Fine-tuning for Youtubevis dataset
python train.py --config=yolact_edge_youtubevis_config

//Train the flow (warping) module
python train.py --config=yolact_edge_vid_trainflow_config --resume=./weights/yolact_edge_youtubevis_847_50000.pth

//Fine tune the network jointly
python train.py --config=yolact_edge_vid_config --resume=./weights/yolact_edge_vid_trainflow_144_100000.pth

**Comment by haotian-liu** [comment]
Yes, it is how we train the models :)

**Comment by hamedmh** [comment]
Hi,
I would like to train the yolact_edge model for instance segmentation using this dataset:

https://github.com/by256/emps

The images are in one folder, and the annotation images are in another folder.
Each object in the annotation image is labeled with a certain value for all of its pixels.
How should I modify this dataset to use it for training of yolact_edge?
Thanks!
Best regards,
Hamed
