### ISSUE TITLE
Doesn't this project training about objects in very small areas?

### ISSUE THREAD

**Issue by JunsukLee** [haotian-liu/yolact_edge#167]
Does training fail if the polygon area of instance segmentation for an object is small?

I tried to train a custom dataset, but it keeps failing.
However, when small area objects were removed a while ago, training is performed.

I'm still training the model, so I'm not sure how well the model will perform, but I'm happy that the training continues. Originally it was because I was failed for training the model.

Are there any parts of the algorithm or implementation code that are sensitive to small objects?

**Comment by JunsukLee** [comment]
This problem is solved.

**Comment by PrajwalCogniac** [comment]
Hey @JunsukLee 
I am facing the same problem , how did you solve it ?
