### ISSUE TITLE
I have a question about "deform_op"

### ISSUE THREAD

**Issue by shoutOutYangJie** [haotian-liu/yolact_edge#18]
我有一个疑问，代码我看过了。在用两个C3特征学习flow之后，flow用来warp，这里我有一点疑问： yolactedge直接将flow resize到指定的h和w，但并没有根据新的h和w算坐标重映射？这理论上来说是不合理的。 举个例子。在30*30的flow上，某一点的预测offset为x和y；那将flow resize到60*60，该点的offset应该重映射到2*x,2*y。但yolactedge没有做这一步。源代码如下：

```
flow = F.interpolate(flow, size=(h, w), mode="area")
pred_feat = deform_op(feat, flow) # warp即： grid sample
```

**Comment by haotian-liu** [comment]
Thank you for the question. The flow field was computed as the relative coordinate scaled by a factor of 8 (which means, the maximum range is [-8, 8], and it will be used to generate sampling map (after divided by 8).

Please refer to the code [here](https://github.com/haotian-liu/yolact_edge/blob/master/layers/warp_utils.py#L59-62).
