### ISSUE TITLE
Google Colab version

### ISSUE THREAD

**Issue by cedro3** [haotian-liu/yolact_edge#2]
Would you please publish the Google Colab version?
I think that if you have the Google Colab version, you can appeal to more people.

**Comment by haotian-liu** [comment]
Thanks for your advice. We will be looking forward to the possibility of porting the model to Google Colab. One of the difficulty here is the TensorRT optimization on Google Colab environment -- whether it can be supported is not clear to me yet.

**Comment by cedro3** [comment]
OK. I look forward to your support.
This issue is closed once.

**Comment by cyrilzakka** [comment]
I might be able to help with this, I already have everything setup in colab save for TensorRT. A quick Google search revealed that it can be installed on Colab with the following: https://github.com/prratadiya/tensorrt-installation-colab

**Comment by haotian-liu** [comment]
@cyrilzakka Thank you for your kind help! I have taken a look at this repo, and this seems to require downloading TensorRT to your Google Drive and link with the Google Drive account. I have found another way to set up TensorRT on Google Colab which seems a bit more convenient to me, and compiled a sample Google Colab (but was doing some debugging so haven't released this earlier). I just released it and updated the [README.md](https://github.com/haotian-liu/yolact_edge#colab-notebook).

If you have better suggestions for Colab, please suggest and share, your kind support is welcomed and appreciated!

**Comment by haotian-liu** [comment]
Updated Colab support in [README.md](https://github.com/haotian-liu/yolact_edge#colab-notebook) in 662d760. If you are interested, please take a look and try it out, thanks!

**Comment by cyrilzakka** [comment]
Will definitely give it a go! Will also try my hand at doing depth estimation using this repo as well. Will report my results when I can.

**Comment by haotian-liu** [comment]
@cyrilzakka thank you!
