### ISSUE TITLE
evaluating random jpg file

### ISSUE THREAD

**Issue by soohunee** [haotian-liu/yolact_edge#20]
I've been trying to evaluate my own random jpg file, however I keep getting errors as below.

Traceback (most recent call last):
  **File "eval.py", line 1282, in <module>
    calibration_dataset = [calibration.pull_item(image_idx)[0] for image_idx in dataset_indices]
  File "eval.py", line 1282, in <listcomp>
    calibration_dataset = [calibration.pull_item(image_idx)[0] for image_idx in dataset_indices]
  File "/home/sh/Desktop/yolact_edge/data/coco.py", line 176, in pull_item
    assert osp.exists(path), 'Image path does not exist: {}'.format(path)
AssertionError: Image path does not exist: ./data/coco/images/000000558840.jpg**

My command line was 
**python eval.py --coco_transfer --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --image=data/coco/images/bird.jpg:output_image.png**

seems like it is trying to find 000000558840.jpg according to the annotation file.
Would there be any way to evaluate my own picture ?

**Comment by haotian-liu** [comment]
This is because it was trying to generate calibration dataset for the TensorRT INT8 conversion. This requires the user to have COCO trainset images and annotations on the disk (which might not be desirable for those who only want to evaluate the model as they are gigs large). To avoid that, we have updated the pipeline and you only need to download a very small calibration set of images sampled from the training set. Please pull the newest commit, download the calibration dataset as in [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md), and rerun the command. Or you can try run without INT8 calibration (thus there is also no need to download the calibration dataset, but with the sacrifice of the speed) as explained in #16.

**Comment by soohunee** [comment]
Thanks for your kind reply.
I downloaded calbration dataset and followed the instructions in INSTALL.md however same result comes up.
Besides downloading calibration dataset, would there be any more things that I have to adjust ?

**Comment by haotian-liu** [comment]
Did you pull the newest commit of the master branch? If so, could you please copy the logs printing on the screen. Thanks.

**Comment by soohunee** [comment]
Sorry, I pulled the newest commit of the master branch and runned again, and now I get this error.

**Traceback (most recent call last):
  File "eval.py", line 1358, in <module>
    net.to_tensorrt_backbone(cfg.torch2trt_backbone_int8, calibration_dataset=calibration_dataset, batch_size=args.trt_batch_size)
  File "/home/sh/Desktop/yolact_edge/yolact.py", line 1560, in to_tensorrt_backbone
    trt_fn = partial(torch2trt, int8_mode=True, int8_calib_dataset=calibration_dataset, strict_type_constraints=True, max_batch_size=batch_size)
NameError: name 'torch2trt' is not defined**

Would this mean torch2trt was not installed correctly?

**Comment by haotian-liu** [comment]
Yes, `torch2trt` (as well as TensorRT) is required for converting the model to TensorRT in our implementation. Please refer to [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md) for instructions. And to make sure the rest part of environment was set up correctly (i.e. without TensorRT), you can try run pure pytorch inference as explained in #16 (although it will be slower, but it makes sure all the files and environments [except for TensorRT] are set up correctly).

**Comment by soohunee** [comment]
when I tried pure pytorch inference the following result came out.

       **|  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box | 31.92 | 51.90 | 49.68 | 46.81 | 43.40 | 39.47 | 34.08 | 27.17 | 18.04 |  7.82 |  0.85 |
  mask | 29.59 | 47.78 | 45.46 | 42.78 | 39.51 | 35.57 | 31.11 | 25.21 | 17.86 |  9.06 |  1.60 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+**

So, it seems like working well.
I will have to take a look at my torch2trt more. Thanks a lot !

**Comment by haotian-liu** [comment]
No problem. Btw just to note that the pure pytorch inference was simply a usage of `_pytorch` config, so you can evaluate on our own jpg file using the same command that you was previously using (with TensorRT) with that config for pure pytorch inference. Thanks.

**Comment by soohunee** [comment]
This really helped a lot ! I really appreciate your kindness.
