### ISSUE TITLE
TypeError: expected np.ndarray (got NoneType)

### ISSUE THREAD

**Issue by starsky68** [haotian-liu/yolact_edge#22]
File "D:/Project/yolact_edge-master/eval.py", line 661, in <listcomp>
    frames = [torch.from_numpy(frame).cuda().float() for frame in frames]
TypeError: expected np.ndarray (got NoneType)

**Comment by starsky68** [comment]
frames = [torch.from_numpy(np.array(frame).astype(float)).cuda().float() for frame in np.array(frames)]

**Comment by cyrilzakka** [comment]
@starsky68 would you mind telling me how you fixed this bug?
