### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by starsky68** [haotian-liu/yolact_edge#23]
File "D:\Project\yolact_edge-master\utils\augmentations.py", line 865, in forward
    img = img.permute(0, 3, 1, 2).contiguous()
RuntimeError: number of dims don't match in permute

**Comment by haotian-liu** [comment]
Could you provide more details (e.g. the command you are using, and the full logs, etc.). Thanks!

**Comment by starsky68** [comment]
Thanks for your reply, my problem is solved

**Comment by Jess1989** [comment]
how do you solve this question? I have the same question now.

**Comment by starsky68** [comment]
> how do you solve this question? I have the same question now.

你可以print一下你的img，看一下是否合理

**Comment by Jess1989** [comment]
好的，谢谢，我已经解决此问题了。谢谢你
----- 原始邮件 -----
发件人：starsky68 ***@***.***>
收件人：haotian-liu/yolact_edge ***@***.***>
抄送人：Jess1989 ***@***.***>,  Comment ***@***.***>
主题：Re: [haotian-liu/yolact_edge] RuntimeError: number of dims don't match in permute (#23)
日期：2021年04月16日 18点48分





how do you solve this question? I have the same question now.



你可以print一下你的img，看一下是否合理



&mdash;
