### ISSUE TITLE
Training Custom datasets

### ISSUE THREAD

**Issue by KennyChen880127** [haotian-liu/yolact_edge#237]
**Describe the bug**

I created a new Json file by filtering the coco data set. It was predictable after training before, but [**Warning: Argumentation output an example with no ground truth. resampling...**] ran out when cacluating mAP...], and it ran last time After 800,000 steps, the box and mask are only in the 20s. Is there something wrong with my steps?

**To Reproduce**
-------------------------------------------------------datasets-------------------------------------------------------
```
my_custom_dataset = dataset_base.copy({
    'name': 'My Dataset',
    'train_images': './data/coco/images/',
    'valid_images': './data/coco/images/',
    'train_info': './data/coco/annotations/merge_train.json',
    'valid_info': './data/coco/annotations/merge_val.json',
    'class_names': ('person', 'car', 'bicycle',),
    'label_map': {1: 1, 2: 2, 3: 3}
})
```
-------------------------------------------------------config-------------------------------------------------------
```
yolact_edge_mobilenetv2_config = yolact_edge_config.copy({
    'name': 'yolact_edge_mobilenetv2',
    'dataset': my_custom_dataset,
    'num_classes': 4,
    'lr': 1e-3,
    'freeze_bn': False,
    'lr_steps': (300000, 500000, 700000),
    'max_iter':800000,
    'backbone': mobilenetv2_backbone
})
```
-------------------------------------------------------command -------------------------------------------------------
`python train.py --config=yolact_edge_youtubevis_config`

**Expected behavior**

When I run 800,000 steps, the mask and box of the map should be very high, and this warning argumentation output an example with no ground truth. resampling...

**Environment:**

 -OS Ubuntu 22.04
 -GPU RTX 2060
 -CUDA Version 11.0

![Screenshot from 2023-04-08 21-26-48](https://user-images.githubusercontent.com/99500847/230727583-f30bd364-8656-41b6-a285-261c531fac64.png)

**Comment by KennyChen880127** [comment]
![Screenshot from 2023-04-08 21-26-48](https://user-images.githubusercontent.com/99500847/230727566-a6184070-6dd6-4956-8609-b4bd1189b5d8.png)

**Comment by PrajwalCogniac** [comment]
Hey @KennyChen880127  what was the solution for this ! Even I am observing the same issue
