### ISSUE TITLE
Parameter Explanation

### ISSUE THREAD

**Issue by cyrilzakka** [haotian-liu/yolact_edge#26]
Hello,

Would you mind explaining the following parameters in `YolAct`? 

```
- selected_layers: The indices of the conv layers to use for prediction.
- pred_scales:     A list with len(selected_layers) containing tuples of scales (see PredictionModule)
- pred_aspect_ratios: A list of lists of aspect ratios with len(selected_layers) (see PredictionModule)
```

If I were to create my own backbone, how should these be modified?

**Comment by cyrilzakka** [comment]
I'm also confused as to what is happening in `construct_backbone(cfg)` in `backbone.py`. Why are you adding extra downsampling layers?

**Comment by haotian-liu** [comment]
Hi, thank you for your interest. These are the same as the original YOLACT, and you can refer to their [repo](https://github.com/dbolya/yolact) and [paper](https://arxiv.org/pdf/1904.02689.pdf) for detailed explanations. Thanks.
