### ISSUE TITLE
evaluating on weights trained with custom dataset

### ISSUE THREAD

**Issue by soohunee** [haotian-liu/yolact_edge#27]
I followed instructions to train with my own custom dataset.
However when I try to evaluate using those trained weight that I got from training my dataset, I get this error.

[01/11 13:41:30 yolact.eval]: Loading model...
WARNING [01/11 13:41:34 yolact.model.load]: Some parameters required by the model do not exist in the checkpoint, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[01/11 13:41:34 yolact.eval]: Model loaded.
[01/11 13:41:34 yolact.eval]: Converting to TensorRT...
[01/11 13:41:34 yolact.eval]: Converting backbone to TensorRT...
[01/11 13:41:37 yolact.eval]: Converting protonet to TensorRT...
[01/11 13:41:37 yolact.eval]: Converting FPN to TensorRT...
[01/11 13:41:37 yolact.eval]: Converting PredictionModule to TensorRT...
[01/11 13:41:52 yolact.eval]: Converted to TensorRT.
Traceback (most recent call last):
  File "eval.py", line 1407, in <module>
    evaluate(net, dataset)
  File "eval.py", line 877, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 590, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/jetson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jetson/yolact_edge/yolact.py", line 1875, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 78, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data, extras)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 168, in fast_nms
    classes = classes[keep]
IndexError: too many indices for tensor of dimension 2

**Comment by haotian-liu** [comment]
There is a warning saying that the prediction / semantic_seg_conv weights are not loaded:
```
WARNING [01/11 13:41:34 yolact.model.load]: Some parameters required by the model do not exist in the checkpoint, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
```

This might account for the IndexError, can you verify the num_classes related configurations as in #10? And if the problem still exists, can you also provide command that you are using?

**Comment by soohunee** [comment]
cfg.num_classes :  10

it says 10, which matches  my class names +1 

custom_dataset = dataset_base.copy({
    'name': 'custom_dataset',

    'train_images': './data/coco/custom/train_coco/',
    'train_info':   './data/coco/custom/train_coco/train_annotations.json',

    'valid_images': './data/coco/custom/valid_coco/',
    'valid_info':   './data/coco/custom/valid_coco/valid_annotations.json',

    'has_gt': True,
    'class_names': ('classid1', 'classid3', 'classid3', 'classid4', 'classid5', 'classid6', 'classid7', 'classid8', 'classid9')
})

yolact_base_config = coco_base_config.copy({
    'name': 'yolact_base',

    # Dataset stuff
    'dataset': custom_dataset,
    'num_classes': len(custom_dataset.class_names) + 1,

it is command line I used when evaluating
python3 eval.py --coco_transfer --trained_model=weights/yolact_edge_746_100000.pth --score_threshold=0.3 --top_k=100 --image=test.jpg:output.jpg

it is command line I used when training
python3 train.py --config=yolact_edge_config --log_folder=./logs/20200108logs/

**Comment by haotian-liu** [comment]
Can you remove the `--coco_transfer` and try again?

**Comment by haotian-liu** [comment]
And for debugging purpose, you can temporarily disable TensorRT with `--disable_tensorrt` during evaluation.

**Comment by soohunee** [comment]
I tested in many ways, and found out that --coco transfer causes this error,

WARNING [01/11 15:11:30 yolact.model.load]: Some parameters required by the model do not exist in the checkpoint, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias

and when I disabled tensorrt, it gave me a correct output.
Seems like indexError is caused by tensorrt.
However, it is weird that tensorrt has problems, cause I evaluated well with the pretrained coco weights.
By the way my device is jetson agx xavier.

**Comment by haotian-liu** [comment]
If you go to the folder where your model is stored `/path/to/model.pth`, you will see multiple TensorRT cache files `/path/to/model.pth.*.trt`. Please delete them as the model weights were altered by `--coco_transfer` when the cache was initially generated.

**Comment by soohunee** [comment]
I deleted all the cache files.trt. Command line and result are as below.

python3 eval.py --trained_model=weights/yolact_edge_1119_150000.pth --score_threshold=0.3 --top_k=100 --image=sample.jpg:output.jpg
[01/11 15:22:56 yolact.eval]: Loading model...
[01/11 15:23:01 yolact.eval]: Model loaded.
[01/11 15:23:01 yolact.eval]: Converting to TensorRT...
[01/11 15:23:45 yolact.eval]: Converting backbone to TensorRT...
[01/11 15:25:35 yolact.eval]: Converting protonet to TensorRT...
[01/11 15:25:47 yolact.eval]: Converting FPN to TensorRT...
Warning: Encountered known unsupported method torch.zeros
[01/11 15:25:56 yolact.eval]: Converting PredictionModule to TensorRT...
[01/11 15:26:06 yolact.eval]: Converted to TensorRT.
cfg.num_classes :  10
Traceback (most recent call last):
  File "eval.py", line 1409, in <module>
    evaluate(net, dataset)
  File "eval.py", line 878, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 591, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/jetson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jetson/yolact_edge/yolact.py", line 1875, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 78, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data, extras)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 168, in fast_nms
    classes = classes[keep]
IndexError: too many indices for tensor of dimension 2

So, till now the correct output was when I used --disable_tensorrt without --coco_transfer. However, these two conditions will lower my performance.

**Comment by haotian-liu** [comment]
If you go to L168 of `./layers/functions/detection.py` (as in fast_nms) and use a try block to print the shape of tensors for (classes and keep)? We haven't encountered such problem previously.
And for "these two conditions will lower my performance" do you mean the FPS drop or the AP drop?

**Comment by soohunee** [comment]
classes = torch.arange(num_classes, device=boxes.device)[:, None].expand_as(keep)
print("\n classes : ", classes.shape)
print("\n keep : ", keep.shape)
classes = classes[keep]

The result was as below.
        
classes :  torch.Size([9, 79])
keep :  torch.Size([9, 79])

I thought disabling tensorrt will lower FPS.

**Comment by haotian-liu** [comment]
You might need to do the try-except.
```python
try:
  classes = ...
  classes = classes[keep]
except:
  print('...', shape)
```

**Comment by soohunee** [comment]
try:
            classes = torch.arange(num_classes, device=boxes.device)[:, None].expand_as(keep)
            classes = classes[keep]
        except:
            print('classes.shape', classes.shape)
            print('keep.shape', keep.shape)

This was the result

classes.shape torch.Size([9, 79])
keep.shape torch.Size([9, 79])
Traceback (most recent call last):
  File "eval.py", line 1409, in <module>
    evaluate(net, dataset)
  File "eval.py", line 878, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 591, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/jetson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jetson/yolact_edge/yolact.py", line 1875, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 78, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data, extras)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/jetson/yolact_edge/layers/functions/detection.py", line 174, in fast_nms
    boxes = boxes[keep]
IndexError: too many indices for tensor of dimension 3

**Comment by haotian-liu** [comment]
This is the same as expected, wierd. What about the data types?
classes.dtype, keep.dtype, are they (torch.int64, torch.bool)

**Comment by soohunee** [comment]
classes.dtype : torch.int64
keep.dtype : torch.bool

yes they are.

**Comment by haotian-liu** [comment]
This seems all correct, and we haven't seen such issue before. If you don't mind (and your data allows), could you send your model weights and the sample image to me that I can reproduce locally to look into this issue. Thanks.

**Comment by haotian-liu** [comment]
And you can send these to me using email: lhtliu#ucdavis

**Comment by haotian-liu** [comment]
Closed upon request.

**Comment by SanjunLiu** [comment]
Traceback (most recent call last):
  File "eval.py", line 1392, in <module>
    evaluate(net, dataset)
  File "eval.py", line 868, in evaluate
    evalimage(net, inp, out)
  File "eval.py", line 580, in evalimage
    preds = net(batch)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/dl/yolact_edge/yolact.py", line 1881, in forward
    assert type(extras) == dict
AssertionError

**Comment by haotian-liu** [comment]
@SanjunLiu Hi, are you using the latest code? Can you pull the latest code and try again, thanks.

**Comment by ntut108318099** [comment]
Sorry , When I want to evaluate my custom model which trained with custom dataset, it showed the same error. 

I have already update the latest code,and run the cooment
```sh
python3 eval.py --yolact_transfer  --trained_model=./weights/yolact_edge_person_49_400000.pth 
```
![image](https://user-images.githubusercontent.com/56862464/104596092-7a3c4300-56ae-11eb-8564-7f6c6b72768a.png)

what can i do to avoid the error ? Thanks~~

And the other problem is when I want to evaluate the pretrain model (yolact_edge_54_800000.pth),it showed the following error.
![image](https://user-images.githubusercontent.com/56862464/104597088-d8b5f100-56af-11eb-852a-a6a87ce34c81.png)

After I track the eval.py code, I found the code  
```sh

        if cfg.torch2trt_fpn or cfg.torch2trt_fpn_int8:
            logger.info("Converting FPN to TensorRT...")
            net.to_tensorrt_fpn(cfg.torch2trt_fpn_int8, batch_size=args.trt_batch_size)
```

So I change the "yolact_edge_config" ,add the "torch2trt_fpn_int8=true".
And it success to evaluate.
Did I change it right ? 

Sorry to bother you ~~

**Comment by haotian-liu** [comment]
@ntut108318099 Regarding your first question, it seems a problem with TensorRT / torch2trt conversion related, and we are currently aware of this issue (which we also heard from another user who trains on the custom dataset). We will let you know once we isolate and fix the issue.
For the second one, it is quite weird, as you can see [here](https://github.com/haotian-liu/yolact_edge/blob/master/data/config.py#L794), `torch2trt_fpn_int8` should exist in all configs, can you verify what has happened to those configs? (did you modify those configs unexpectedly by chance?)
And the code should stop executing after the evaluation finishes, and I do not see a reason why this will execute twice (can you provide the command you are using and verify that you are not making changes to `eval.py`? thanks.)

**Comment by ntut108318099** [comment]
@haotian-liu thanks for your quick reply first.

About first question, I will wait for your fix issue. Thanks a lot ~~

About the others question,I rebuild the config and eval.py. It didn't show the error again,maybe I modify the code  unexpectedly by chance...

Sorry to bother you~ about the custom dataset issue , your hard work I really appreciate.

**Comment by haotian-liu** [comment]
@ntut108318099 I am grad to hear that your problem has been resolved. We will keep you updated when the TensorRT related issue is investigated and fixed. Thank you for your interest in and support for our work.

**Comment by ntut108318099** [comment]
@haotian-liu  sorry, I have another question to ask. You update the `train.py`. If I want to retrain the model , do I need to add the command about `--yolact_transfer` ? 

The following command is I set .
```sh
python3  train.py --config=yolact_edge_config 
```

**Comment by haotian-liu** [comment]
@ntut108318099 No you don't need that. You only need that when you are using a model trained with YOLACT.

**Comment by ntut108318099** [comment]
@haotian-liu  so when I use the model  trained by train.py , I didn't use `--yolact_transfer` on eval.py.

But why `yolact_edge_54_800000.pth` need to set `--yolact_transfer` command ? 
Did it not trained with train.py in yolact_edge  ?

**Comment by haotian-liu** [comment]
@ntut108318099 Because I just took that model from YOLACT.

**Comment by haotian-liu** [comment]
@soohunee @ntut108318099 Hi, we have proposed a solution towards the IndexError issue, please see the newest commits (8569ad7, 1bbdf5f). Hope this resolves the issue, thanks.

**Comment by ntut108318099** [comment]
@haotian-liu  Thanks for your fixed issue.

I updated the new version , but it showed the new error.
The following is the result.
![image](https://user-images.githubusercontent.com/56862464/104834922-e5b82780-58dd-11eb-864e-e31f9a8b3ce8.png)

Thanks for your hard work ~~

**Comment by haotian-liu** [comment]
@ntut108318099 This is weird. I took a look at the tensor here, they seem to be 1-D tensor? Can you print the shape of both classes and idx tensor for me? Thanks.

**Comment by haotian-liu** [comment]
@ntut108318099 ... And can you also print idx.min() and idx.max() for me.

**Comment by ntut108318099** [comment]
@haotian-liu  did you mean this ?
![image](https://user-images.githubusercontent.com/56862464/104835335-dbe3f380-58e0-11eb-9381-514e4748f04d.png)

**Comment by haotian-liu** [comment]
@ntut108318099 This seems some issue with TensorRT or torch2trt. So just to confirm, this occurs when you enable TensorRT, and if `--disable_tensorrt`, it does not occur?

**Comment by ntut108318099** [comment]
@haotian-liu  yes , when I ```--disable_tensorrt``` , it does not occur. It succeed ~

So it seems TensorRT or torch2trt issue... 
Thanks.

**Comment by haotian-liu** [comment]
@ntut108318099 I proposed a potential fix -- can you switch to `haotian-dev` branch and pull the latest commit and have a try?

**Comment by ntut108318099** [comment]
@haotian-liu  It ran successful for a while, and it stopped .
Here's the result.
![image](https://user-images.githubusercontent.com/56862464/104835811-1602c480-58e4-11eb-8ec7-84162af95ab2.png)

**Comment by haotian-liu** [comment]
@ntut108318099 What's the shape of proto_data and masks?

**Comment by haotian-liu** [comment]
@ntut108318099 And will you see this error if disabling TensorRT?

**Comment by ntut108318099** [comment]
@haotian-liu  
When it stopped,the shape of masks are different with the other result. 

![image](https://user-images.githubusercontent.com/56862464/104836011-76decc80-58e5-11eb-8a68-abec32d42b14.png)

If I disable tensorrt , it won't show the error. It succeed to eval.

**Comment by haotian-liu** [comment]
@ntut108318099 If without proprietary issue, can you email me your trained model, as well as the specific sample image the error occurs (you can verify it is the one using `--image=selected.jpg` if you can see the same error). Thanks.

**Comment by ntut108318099** [comment]
@haotian-liu  I am trying to use the model with usb camera. To check if the model can use or not.
I will email you my trained model if the error still show by the other way. 

Thanks a lot .

**Comment by ntut108318099** [comment]
@haotian-liu  I emailed you my trianed model.

Please let me know if you received successfully.

**Comment by soohunee** [comment]
The error showed up.
WARNING [01/18 11:07:23 yolact.layers.detect]: Encountered IndexError as mentioned in https://github.com/haotian-liu/yolact_edge/issues/27. Flattening predictions to avoid error, please verify the outputs. If there are any problems you met related to this, please report an issue.

however the output was pretty good. Would flattening prediction affect any perfrmance ?

**Comment by haotian-liu** [comment]
@soohunee This warning message is intentional as this seems a TensorRT issue and we found a way to get around with it. But normally the output should just be fine.

**Comment by chingi071** [comment]
Hello, when I use the model I trained to execute the following command to evaluate, there will be an error and no output.
```
$ python eval.py --trained_model=weights/yolact_edge_mobilenetv2_159_8000.pth --score_threshold=0.3 --top_k=100 --image=pig_test.jpg --use_fp16_tensorrt 
Config not specified. Parsed yolact_edge_mobilenetv2_config from the file name.

[03/05 16:30:23 yolact.eval]: Loading model...
[03/05 16:30:25 yolact.eval]: Model loaded.
[03/05 16:30:25 yolact.eval]: Converting to TensorRT...
[03/05 16:30:25 yolact.eval]: Converting backbone to TensorRT...
[03/05 16:30:46 yolact.eval]: Converting protonet to TensorRT...
[03/05 16:30:49 yolact.eval]: Converting FPN to TensorRT...
Warning: Encountered known unsupported method torch.zeros
[03/05 16:30:53 yolact.eval]: Converting PredictionModule to TensorRT...
[03/05 16:30:58 yolact.eval]: Converted to TensorRT.
WARNING [03/05 16:30:58 yolact.layers.detect]: Encountered IndexError as mentioned in https://github.com/haotian-liu/yolact_edge/issues/27. Flattening predictions to avoid error, please verify the outputs. If there are any problems you met related to this, please report an issue.
```
But when I use `--disable_tensorrt`, it can output normally.
I also switch to `haotian-dev `branch to try, , but there are still errors.
```
Traceback (most recent call last):
  File "eval.py", line 1248, in <module>
    evaluate(net, dataset)
  File "eval.py", line 885, in evaluate
    evalimage(net, args.image)
  File "eval.py", line 596, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/aderd/anaconda3/envs/pytorch_v37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/aderd/joy/yolact_edge-haotian-dev/yolact.py", line 1797, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs)
  File "/home/aderd/joy/yolact_edge-haotian-dev/layers/functions/detection.py", line 75, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/aderd/joy/yolact_edge-haotian-dev/layers/functions/detection.py", line 105, in detect
    boxes, masks, classes, scores = self.fast_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/aderd/joy/yolact_edge-haotian-dev/layers/functions/detection.py", line 209, in fast_nms
    if not cfg.use_tensorrt_safe_mode:
AttributeError: 'Config' object has no attribute 'use_tensorrt_safe_mode'
```
I also disable TensorRT for FPN, but it still doesn’t work.
```
{
    'torch2trt_fpn': False,
    'torch2trt_fpn_int8': False,
}

```
I train a category, and I confirmed that cfg.num_classes is correct. This is my data setting in config.
```
my_custom_dataset = dataset_base.copy({
    'name': 'My Dataset',

    'train_images': './data/',
    'train_info':   './data/annotations.json',

    'valid_images': './data/',
    'valid_info':   './data/annotations.json',

    'has_gt': True,
    'class_names': ('classid1'),
    'label_map': {1:1}

})
```
```
yolact_edge_mobilenetv2_config = yolact_edge_config.copy({
    'name': 'yolact_edge_mobilenetv2',
    'dataset': my_custom_dataset,
    'num_classes':2,
    #'torch2trt_fpn': False,
    #'torch2trt_fpn_int8': False,
    'max_size': 550,
    'lr_steps': (2800, 6000, 7000, 7500),
    'max_iter': 8000,
    'backbone': mobilenetv2_backbone
})
```
Can i ask you what should i do? thank you.

**Comment by chingi071** [comment]
Hello, I just tried the `haotian-dev` branch and executed this command. It can output normally now.
`$python eval.py --trained_model=weights/yolact_edge_mobilenetv2_159_8000.pth --score_threshold=0.3 --top_k=100 --image=pig_test.jpg --use_fp16_tensorrt --use_tensorrt_safe_mode`
I want to ask what is the difference between this branch and master? Why can't it output normally when using master to execute `--use_fp16_tensorrt`?

**Comment by haotian-liu** [comment]
@chingi071 Grad that you had your problem solved! These two branches are actually the same at this point. 

Seems at one point you had an issue with `cfg.use_tensorrt_safe_mode`. It could be that you accidentally removed `'use_tensorrt_safe_mode': False` from `data/config.py`.

I am not sure if you noticed any other difference between `master` and `haotian-dev`. Because they are currently on the SAME commit.

**Comment by chingi071** [comment]
Thank you for your reply! I found out that my master version is old, so there are differences.
I would like to ask why it is necessary to use` --use_tensorrt_safe_mode` to successfully output?
Why can't the output be displayed successfully by only using the following command? Thank you again for your contribution and help!
`$python eval.py --trained_model=weights/yolact_edge_mobilenetv2_159_8000.pth --score_threshold=0.3 --top_k=100 --image=pig_test.jpg --use_fp16_tensorrt`

**Comment by haotian-liu** [comment]
@chingi071 Please see [here](https://github.com/haotian-liu/yolact_edge#handling-inference-error-when-using-tensorrt) for explanations why we need this option.

**Comment by chingi071** [comment]
I understand, thank you very much!

**Comment by xuatpham** [comment]
hello @haotian-liu , thanks for your effort.

- I tried with the pre-trained model that you provided in this repo and able to run the model with and without TRT mode, all are good.
But
- I'm having an issue with tensorrt on a model trained on custom data. I'm running on agx xavier. 
I was able to run the model without TRT mode.
But
Problems occurred when I tried to run the model in TRT mode. I went through almost issues and I'm now able to run the custom model in TRT mode with the args `use_tensorrt_safe_mode`
But
The result of the TRT model mode is totally wrong. It seems like all the results are repeated for all images. This problem is the same for master and haotian-dev branches. 

Help to advice me what should I investigate now, thanks.

**Comment by haotian-liu** [comment]
@xuatpham  Maybe I would try removing the TensorRT cache (under `weights` folder, files ending with `.trt`) to see if the TensorRT model caches are corrupted. If that does not work, I would dig to see how the TensorRT model outputs for each different layer are different from the ones without TensorRT.

**Comment by xuatpham** [comment]
@haotian-liu  thanks for quick response

yes, I always remove all previous `.trt` in the weights folder before every new run.
btw, the model was trained as a single object, and class_names was defined as `(class_name_id1, )` .

Thanks for advice.

**Comment by haotian-liu** [comment]
@xuatpham 
The definition for the class_names looks good to me. Sorry that I am not sure what is happening with your custom model (it is strange that they are outputing the same thing for different inputs)

**Comment by haotian-liu** [comment]
@xuatpham 
The definition for the class_names looks good to me. Sorry that I am not sure what is happening with your custom model (it is strange that they are outputing the same thing for different inputs)
