### ISSUE TITLE
no  instances_train2017.json file 

### ISSUE THREAD

**Issue by qingjiudd** [haotian-liu/yolact_edge#3]
I just want to test a picture of myself，When I run the “python eval.py --coco_transfer --trained_model=weights/yolact_edge_resnet50_54_800000.pth --score_threshold=0.3 --top_k=100 --image=0.jpg:0_out.jpg
” command, I get error  “No such file or directory: './data/coco/annotations/instances_train2017.json'
”
I don't want to download the coco dataset

**Comment by haotian-liu** [comment]
Currently, if you want to run the YolactEdge with TensorRT, the int8 conversion requires the model calibrated with dataset images -- which are random images sampled from training dataset. You can try running the model without TensorRT optimization, or calibrate with your own calibration dataset (not currently supported yet, in our TODO).

**Comment by haotian-liu** [comment]
Please refer to updated documentation in ea3b3030a45f10b6a6dea81dded3c4017de93481.
