### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by zeroRains** [haotian-liu/yolact_edge#30]
I want to use the pretrain mode in eval.py to eval a image in colab.I use the model which the repositorise provide for us,But it have some problem like this 
![image](https://user-images.githubusercontent.com/57100978/104795640-ffc50d80-57ea-11eb-8e73-13e4e4bf37b7.png)
How can I sovle it ?

**Comment by haotian-liu** [comment]
`--yolact_transfer` is needed to transfer YOLACT-trained weights, and you need to disable TensorRT if it is not compiled on Colab.

**Comment by zeroRains** [comment]
how to adisable TensorRT,I removed the --yolact_transfer but it also dosen't work.
![image](https://user-images.githubusercontent.com/57100978/104799420-ed0e0100-5809-11eb-9525-9f1463250b5c.png)

**Comment by haotian-liu** [comment]
Hi, you will need `--yolact_transfer`. With that, you should not be seeing the two warnings. And you need to disable TensorRT (if you have not compiled TensorRT on Colab) with `--disable_tensorrt`.

**Comment by zeroRains** [comment]
Oh!It have been solved! Thanks for your help!
