### ISSUE TITLE
I am get only 2 fps on Jetson Xavier...

### ISSUE THREAD

**Issue by sdimantsd** [haotian-liu/yolact_edge#32]
Hi, thanks for you project :-)
I am try to eval on jetson xavier, this is the command i used and the results..
```
python3 eval.py --yolact_transfer --trained_model=./weights/yolact_edge_54_800000.pth --video=/home/ws/videos/20201015_175745_ra283.mp4:/home/ws/asd.mp4
Config not specified. Parsed yolact_edge_config from the file name.

[01/20 15:41:00 yolact.eval]: Loading model...
[01/20 15:41:05 yolact.eval]: Model loaded.
[01/20 15:41:05 yolact.eval]: Converting to TensorRT...
calib_folder: /home/ws/sdcard/coco/calib_images/
[01/20 15:41:56 yolact.eval]: Converting backbone to TensorRT...
[01/20 15:45:38 yolact.eval]: Converting protonet to TensorRT...
[01/20 15:45:57 yolact.eval]: Converting FPN to TensorRT...
Warning: Encountered known unsupported method torch.zeros
[01/20 15:46:06 yolact.eval]: Converting PredictionModule to TensorRT...
[01/20 15:46:15 yolact.eval]: Converted to TensorRT.
```
I am get only ~2 FPS.

But when i used this command:
`python3 eval.py --yolact_transfer --trained_model=weights/yolact_edge_54_800000.pth --benchmark -
-max_images=1000
Config not specified. Parsed yolact_edge_config from the file name.

loading annotations into memory...
Done (t=0.88s)
creating index...
index created!
[01/20 15:49:51 yolact.eval]: Loading model...
[01/20 15:49:55 yolact.eval]: Model loaded.
[01/20 15:49:55 yolact.eval]: Converting to TensorRT...
[01/20 15:49:55 yolact.eval]: Converting backbone to TensorRT...
[01/20 15:49:58 yolact.eval]: Converting protonet to TensorRT...
[01/20 15:49:58 yolact.eval]: Converting FPN to TensorRT...
[01/20 15:49:58 yolact.eval]: Converting PredictionModule to TensorRT...
[01/20 15:50:14 yolact.eval]: Converted to TensorRT.

Processing Images  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░     73 /   1000 ( 7.30%)    25.54 fps`

I get ~25 FPS
What the different?

Also i am not shure i understand the article. did you are using 2 things to optimized YOLACT (tensorrt int8 and the video thing) or more?

Thanks

**Comment by sdimantsd** [comment]
Update, on images it's much more faster (20-30 FPS, it's depend if i measure the all process (reading and saving the image, and so on or just measure the network time).

**Comment by sdimantsd** [comment]
But the video is still VERY slow...
And also this question:

> Also i am not shure i understand the article. did you are using 2 things to optimized YOLACT (tensorrt int8 and the video thing) or more?

Thanks! :-D

**Comment by haotian-liu** [comment]
For the video FPS, you might want to verify the resolution of the video -- the processing speed is related to the input resolution, and if it is too large, the FPS will be affected.
For the optimization part, it is correct: we have two main optimizations: (1) TensorRT related optimization and calibration; (2) video redundancy.

**Comment by sdimantsd** [comment]
@haotian-liu 
Thanks, i will check the FPS on the video.
What is the purpose of the calibration part (in TensorRT and in video redundancy)?
It is needed only for YOLACT weights? (if i will train yolact edge i still need it?)
According to the article the main optimize is the TensorRT optimization, right? (about 300%-400% improvements) and the video redundancy is about 200%.
Am I right?
To use the video redundancy optimization what will by the different in the final results if I train with my own dataset (steels images) and use the ytvis calib images or train with my own video dataset (of the prev and next frames)?

Thanks very match!

**Comment by haotian-liu** [comment]
@sdimantsd Calibration is needed for TensorRT INT8 conversion (no need for FP16 conversion). If you are working on the images, then you can use the image-based model; for video-based model, you will achieve the best performance when two optimization are used altogether.

**Comment by sdimantsd** [comment]
Thanks,
My question is if I am evaluate on videos, did I need a video dataset? or can I train with the regular image dataset and do the calibration using the youtube video calib image?
And also with the TensorRT int8, if I trained it with TensorRT int8, do I need this calibration?

Thanks

**Comment by haotian-liu** [comment]
@sdimantsd If you train on the image dataset, you can simply use the image-based model (and calibrate with COCO images or some sample images from your video, see `--calib_images`).
You do **not** need to **train** with TensorRT, simply train the model without TensorRT in full precision, and convert the trained model to TensorRT.

**Comment by sdimantsd** [comment]
Thank you for your patience!
I'm not sure I'm explaining myself properly, I'll try again.
At the client I use the network to identify objects in the video, but my dataset is just frames (without the prev&next).
What should I do? can I train with my dataset and then convert it to _vid_config somehow?

**Comment by sdimantsd** [comment]
One more thing, how the calib works?

**Comment by haotian-liu** [comment]
@sdimantsd So if the source dataset contains separate frames only, **and you have no way to define the prev&next relationship**, you can just regard it as the image dataset, train and evaluate using the image config (w/o _vid_). It could be possible to train the warping module separately, but it is not what YolactEdge is designed as, thus the performance might be sub-optimal (you could try if you are interested in this). Thus the simplest and the safest option for this case is to use the image-model config.

For the detailed explanation of calibration, please refer to [TensorRT](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html) website.

Thanks.

**Comment by sdimantsd** [comment]
OK.
Thank you very much.
