### ISSUE TITLE
is it possible to train on custom dataset that doesn't have segmentation mask ?

### ISSUE THREAD

**Issue by purvang3** [haotian-liu/yolact_edge#33]
my dataset only contains bbox information along with klass and other information in coco json formate. but it doesn't consist segmentation mask in annotations. is it still possible to train on my custom dataset?

**Comment by haotian-liu** [comment]
If you modify the code to remove the mask branch (and corresponding losses), you could possibly train a object detection network on your custom dataset. But YolactEdge is not designed for that, so the performance might not be optimal.
