### ISSUE TITLE
Performance on Jetson Nano

### ISSUE THREAD

**Issue by Nerdyvedi** [haotian-liu/yolact_edge#39]
Hi, 
Thanks for open sourcing such a great work.

I wanted to enquire about the performance of model on Jetson Nano(Would buy if the performance is good :) )
Could you report the fps from grabbing the frames to displaying it (if possible with 720p resolution)?

Also, I only need to detect Person class.

Thanks

**Comment by haotian-liu** [comment]
Hi, unfortunately I currently do not have a Jetson Nano on my hand. It might have a bit lower performance than Jetson Xavier.

**Comment by sdimantsd** [comment]
In my experiment (with other networks) Jetson Nano is lower 7 times then Jetson Xavier.
In yolact edge I measure the times in Jetson Xavier and Jetson Nano **(the times in ONLY THE NETWORK! not include the reading the frames, transfer to cuda and display)**
Input size: 500x500, times in milliseconds.

![image](https://user-images.githubusercontent.com/29533264/105952811-cad27980-607a-11eb-9e87-be311c77a08f.png)

'yolact edge video real' it's:
`([yolact edge video for not iframe]*4 + [yolact edge])/5`

**Comment by sdimantsd** [comment]
In my experiment (with other networks) Jetson Nano is lower 7 times then Jetson Xavier.
In yolact edge I measure the times in Jetson Xavier and Jetson Nano (the times in ONLY THE NETWORK! not include the reading the frames, transfer to cuda and display)
Input size: 500x500, times in milliseconds.

![image](https://user-images.githubusercontent.com/29533264/105953011-26046c00-607b-11eb-8480-e5636d7a0a9b.png)


'yolact edge video real' it's:
`([yolact edge video for not iframe]*4 + [yolact edge])/5`

I did't check the video improvements on jetson nano.

@haotian-liu 
Do you want to buy Jetson nano? Nvidia sell it in 99$

**Comment by Nerdyvedi** [comment]
@haotian-liu Could you please share the total fps(Reading and displaying output) on Xavier?

**Comment by haotian-liu** [comment]
@sdimantsd Thank you for your help!
@Nerdyvedi Please refer to our paper (some of them are also on [README.md](https://github.com/haotian-liu/yolact_edge/blob/master/README.md)) for the numbers on the Xavier, thanks.

**Comment by sdimantsd** [comment]
@haotian-liu
 The numbers in your paper it's the times include the reading and display?

**Comment by haotian-liu** [comment]
@sdimantsd It does not include data loading and the displaying. With the naive implementation, it is around 22 FPS with cameras inputs -- you can see from our live demo [here](https://www.youtube.com/watch?v=GBCK9SrcCLM).

**Comment by sdimantsd** [comment]
Thanks
