### ISSUE TITLE
Best way to use flow net for increasing FPS

### ISSUE THREAD

**Issue by Ilyabasharov** [haotian-liu/yolact_edge#43]
Ciao! I downloaded weights [YouTube VIS models] (for example, [link](https://drive.google.com/file/d/1mSxesVaMmYc13cPHiEnRvubPxy8WBjJW/view?usp=sharing)). How to run the method using flow net for video?

Code is:
`
args.trained_model` = "./weights/weight_vis.pth"
args.yolact_transfer = True
args.disable_tensorrt = False
args.use_fp16_tensorrt = True
args.video_multiframe = 2
args.trt_batch_size = 2
args.calib_images="./calib_images"
torch.set_default_tensor_type('torch.cuda.FloatTensor')
logger.info('Loading model...')
net = Yolact(training=False)
net.load_weights(args.trained_model, args=args)
`

The problem is:
`
WARNING [01/29 10:49:30 yolact.model.load]: Some parameters in the checkpoint are not used: spa.refine_convs.0.0.weight, spa.refine_convs.0.0.bias, spa.refine_convs.1.0.weight, spa.refine_convs.1.0.bias, flow_net_pre_convs.convs.0.0.weight, flow_net_pre_convs.convs.0.0.bias, flow_net.conv1.0.0.weight, flow_net.conv1.0.0.bias, flow_net.conv1.1.0.weight, flow_net.conv1.1.0.bias, flow_net.conv2.0.0.weight, flow_net.conv2.0.0.bias, flow_net.conv2.1.0.weight, flow_net.conv2.1.0.bias, flow_net.conv3.0.0.weight, flow_net.conv3.0.0.bias, flow_net.conv3.1.0.weight, flow_net.conv3.1.0.bias, flow_net.pred3.conv.weight, flow_net.pred3.scale.weight, flow_net.pred3.scale.bias, flow_net.pred3.bias.weight, flow_net.pred3.bias.bias, flow_net.pred2.conv.weight, flow_net.pred2.scale.weight, flow_net.pred2.scale.bias, flow_net.pred2.bias.weight, flow_net.pred2.bias.bias, flow_net.pred1.conv.weight, flow_net.pred1.scale.weight, flow_net.pred1.scale.bias, flow_net.pred1.bias.weight, flow_net.pred1.bias.bias, flow_net.upfeat3.weight, flow_net.upflow3.weight, flow_net.upfeat2.weight, flow_net.upflow2.weight
`

**Comment by haotian-liu** [comment]
You need to use the video-based configs: ``--config yolact_edge_vid_config``

**Comment by Ilyabasharov** [comment]
@haotian-liu 

from eval import *
from utils.logging_helper import setup_logger
`
parse_args(["--config=yolact_edge_vid_config"])

from eval import args
from utils.tensorrt import convert_to_tensorrt

setup_logger(logging_level=logging.INFO)
logger = logging.getLogger("yolact.eval")

args.trained_model = "./weights/double/yolact_edge_vid_144_100000.pth"
args.yolact_transfer = True
args.disable_tensorrt = False
args.use_fp16_tensorrt = True
args.video_multiframe = 2
args.trt_batch_size = 2

args.calib_images="./calib_images"

torch.set_default_tensor_type('torch.cuda.FloatTensor')

logger.info('Loading model...')
net = Yolact(training=False)
net.load_weights(args.trained_model, args=args)
`

What did I do wrong? The problem is the same as was. Thank you for your help!

**Comment by haotian-liu** [comment]
I did not see the error. Can you provide the full log?

**Comment by Ilyabasharov** [comment]
@haotian-liu It seems to me that the network weights didn't fit with the model. Am I wrong? Thank you for your response !

`[01/29 22:05:37 yolact.eval]: Loading model...
WARNING [01/29 22:05:41 yolact.model.load]: Some parameters in the checkpoint are not used: spa.refine_convs.0.0.weight, spa.refine_convs.0.0.bias, spa.refine_convs.1.0.weight, spa.refine_convs.1.0.bias, flow_net_pre_convs.convs.0.0.weight, flow_net_pre_convs.convs.0.0.bias, flow_net.conv1.0.0.weight, flow_net.conv1.0.0.bias, flow_net.conv1.1.0.weight, flow_net.conv1.1.0.bias, flow_net.conv2.0.0.weight, flow_net.conv2.0.0.bias, flow_net.conv2.1.0.weight, flow_net.conv2.1.0.bias, flow_net.conv3.0.0.weight, flow_net.conv3.0.0.bias, flow_net.conv3.1.0.weight, flow_net.conv3.1.0.bias, flow_net.pred3.conv.weight, flow_net.pred3.scale.weight, flow_net.pred3.scale.bias, flow_net.pred3.bias.weight, flow_net.pred3.bias.bias, flow_net.pred2.conv.weight, flow_net.pred2.scale.weight, flow_net.pred2.scale.bias, flow_net.pred2.bias.weight, flow_net.pred2.bias.bias, flow_net.pred1.conv.weight, flow_net.pred1.scale.weight, flow_net.pred1.scale.bias, flow_net.pred1.bias.weight, flow_net.pred1.bias.bias, flow_net.upfeat3.weight, flow_net.upflow3.weight, flow_net.upfeat2.weight, flow_net.upflow2.weight
WARNING [01/29 22:05:41 yolact.model.load]: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[01/29 22:05:41 yolact.eval]: Model loaded.
[01/29 22:05:41 yolact.eval]: Converting to TensorRT...
[01/29 22:05:41 yolact.eval]: Converting backbone to TensorRT...`

**Comment by haotian-liu** [comment]
This is weird, did you make any change to the config and the code? Can you directly run eval.py with the commands provided in [README.md](https://github.com/haotian-liu/yolact_edge/blob/master/README.md)?

**Comment by Ilyabasharov** [comment]
@haotian-liu I didn't change your code. In README.md you never specified the configuration `--config yolact_edge_vid_config` in [Evaluation](https://github.com/haotian-liu/yolact_edge#evaluation). Please, send the right command which used [YolactEdge | R-101-FPN YouTube VIS (FlowNet)](https://drive.google.com/file/d/1mSxesVaMmYc13cPHiEnRvubPxy8WBjJW/view?usp=sharing) to run the model. Sorry for the misunderstanding!

**Comment by haotian-liu** [comment]
If you train with the model file without modifying the file name, it will automatically detect which config to use. But you are manually renaming the model file name and this prevent the code from performing that automatic config selection. For the commands to use, please refer to [here](https://github.com/haotian-liu/yolact_edge#evaluation). Thanks.

**Comment by Ilyabasharov** [comment]
Thanks, I got it! I'm sorry!
