### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by sdimantsd** [haotian-liu/yolact_edge#44]
Hi, 
I trained my own dataset using yolact edge trainer.
When I try to eval I get this error:
```
python3 eval.py --use_fp16_tensorrt --trained_model=./weights/yolact_nets_shuk_resnet101_im320_9_130000.pth --images=/home/ws/images/imgs_in/:/home/ws/imgs_out --top_k=20 --score_threshold=0.3
Config not specified. Parsed yolact_nets_shuk_resnet101_im320_config from the file name.

[01/31 09:54:40 yolact.eval]: Loading model...
[01/31 09:54:50 yolact.eval]: Model loaded.
[01/31 09:54:50 yolact.eval]: Converting to TensorRT...
[01/31 09:54:50 yolact.eval]: Converting backbone to TensorRT...
[01/31 09:55:35 yolact.eval]: Converting protonet to TensorRT...
[01/31 09:55:41 yolact.eval]: Converting FPN to TensorRT...
Warning: Encountered known unsupported method torch.zeros
[01/31 09:55:51 yolact.eval]: Converting PredictionModule to TensorRT...
[01/31 09:56:02 yolact.eval]: Converted to TensorRT.

WARNING [01/31 09:56:03 yolact.layers.detect]: Encountered IndexError as mentioned in https://github.com/haotian-liu/yolact_edge/issues/27. Flattening predictions to avoid error, please verify the outputs. If there are any problems you met related to this, please report an issue.
/home/ws/images/imgs_in/13.jpg -> /home/ws/imgs_out/13.png
Traceback (most recent call last):
  File "eval.py", line 1246, in <module>
    evaluate(net, dataset)
  File "eval.py", line 887, in evaluate
    evalimages(net, inp, out)
  File "eval.py", line 619, in evalimages
    evalimage(net, path, out_path)
  File "eval.py", line 594, in evalimage
    preds = net(batch, extras=extras)["pred_outs"]
  File "/home/ws/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ws/DL/yolact_edge/yolact.py", line 1879, in forward
    outs_wrapper["pred_outs"] = self.detect(pred_outs, extras=extras)
  File "/home/ws/DL/yolact_edge/layers/functions/detection.py", line 77, in __call__
    decoded_boxes = decode(loc_data[batch_idx], prior_data)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/ws/DL/yolact_edge/layers/box_utils.py", line 264, in decode
        boxes = torch.cat((
            priors[:, :2] + loc[:, :2] * variances[0] * priors[:, 2:],
            priors[:, 2:] * torch.exp(loc[:, 2:] * variances[1])), 1)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        boxes[:, :2] -= boxes[:, 2:] / 2
        boxes[:, 2:] += boxes[:, :2]
RuntimeError: CUDA error: an illegal memory access was encountered

```
If I use --disable_tensorrt, it's works without any error.

**Comment by haotian-liu** [comment]
It seems that for some of the models, the TensorRT conversion will cause some of the issues. Investigating the issue as in #38 and #42.

**Comment by sdimantsd** [comment]
Oh OK.
Thanks :-)

**Comment by haotian-liu** [comment]
Hi I am currently closing this issue, and merge the discussion related to TensorRT conversion issue after training on a custom dataset to this issue #47 as it is quite hard for me to track so many open issues. Hope you understand, thanks.

**Comment by haotian-liu** [comment]
And I have posted a follow-up about the possible cause in #47, could you take a look and see if you could provide a bit more information for me to investigate, thanks.

**Comment by haotian-liu** [comment]
Hi, can you provide me with your training setting, thanks.

(1) number of GPUs used to train the model
(2) batch size per GPU
(3) learning rate
(4) number of iterations trained
(5) number of categories in the dataset
(6) number of samples in the dataset.

**Comment by haotian-liu** [comment]
I somehow figured out that this is related to multiple training instability, and it also exists in original YOLACT https://github.com/dbolya/yolact/issues/586, https://github.com/dbolya/yolact/issues/222, https://github.com/dbolya/yolact/issues/340.
I have applied Daniel's fix towards this issue with some modifications, and have pushed to the `haotian-dev` branch.

You could try one of the two followings to see if your issue has been resolved:
(1) train using a single GPU
(2) train with the latest code in `haotian-dev` branch with multiple GPUs.

If the issue persists, please **reply directly to #47** (this will be the main thread to deal with related issues for now) with the following information, thanks.
(1) number of GPUs used to train the model
(2) batch size per GPU
(3) learning rate
(4) number of iterations trained
(5) dataset-related information (# of classes, # of training images).

**Comment by sdimantsd** [comment]
Thanks
