### ISSUE TITLE
using Jetson Nx  error

### ISSUE THREAD

**Issue by weiluonika** [haotian-liu/yolact_edge#45]
(torch_env) inspur@inspur-desktop:~/torch_long/yolact_edge$ python eval.py --trained_model=/home/inspur/torch_long/yolact/weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --image=/home/inspur/torch_long/yolact/1.jpg:output_image.png
Config not specified. Parsed yolact_edge_config from the file name.

[02/01 11:33:58 yolact.eval]: Loading model...
/home/inspur/torch_long/torch_env/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/inspur/torch_long/torch_env/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/inspur/torch_long/torch_env/lib/python3.6/site-packages/torch/jit/_recursive.py:165: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
[02/01 11:34:08 yolact.eval]: Model loaded.
[02/01 11:34:08 yolact.eval]: Converting to TensorRT...
Traceback (most recent call last):
  File "eval.py", line 1241, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/home/inspur/torch_long/yolact_edge/utils/tensorrt.py", line 76, in convert_to_tensorrt
    calibration_dataset = pull_calib_dataset(calib_images)
  File "/home/inspur/torch_long/yolact_edge/utils/tensorrt.py", line 63, in pull_calib_dataset
    calibration_dataset = torch.stack(images)
RuntimeError: stack expects a non-empty TensorList

########################
Who can answer me?

**Comment by haotian-liu** [comment]
You did not download the calibration images for INT8 conversion. See [here](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md).

**Comment by weiluonika** [comment]
> You did not download the calibration images for INT8 conversion. See [here](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md).

Thanks for your quick reply, we have solved this problem, but there is another problem when running  eval.py.


#####
[02/01 16:13:45 yolact.eval]: Loading model...
[02/01 16:13:54 yolact.eval]: Model loaded.
[02/01 16:13:54 yolact.eval]: Converting to TensorRT...
[02/01 16:15:08 yolact.eval]: Converting backbone to TensorRT...
[TensorRT] ERROR: FAILED_ALLOCATION: std::bad_alloc
Traceback (most recent call last):
  File "eval.py", line 1241, in <module>
    convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
  File "/home/inspur/torch_long/yolact_edge/utils/tensorrt.py", line 152, in convert_to_tensorrt
    net.to_tensorrt_backbone(cfg.torch2trt_backbone_int8, calibration_dataset=calibration_dataset, batch_size=args.trt_batch_size)
  File "/home/inspur/torch_long/yolact_edge/yolact.py", line 1571, in to_tensorrt_backbone
    self.trt_load_if("backbone", trt_fn, [x], int8_mode, batch_size=batch_size)
  File "/home/inspur/torch_long/yolact_edge/yolact.py", line 1554, in trt_load_if
    self.save_trt_cached_module(module, module_name, int8_mode, batch_size=batch_size)
  File "/home/inspur/torch_long/yolact_edge/yolact.py", line 1545, in save_trt_cached_module
    torch.save(module.state_dict(), module_path)
  File "/home/inspur/torch_long/torch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 902, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/home/inspur/torch_long/torch_env/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 419, in _on_state_dict
    state_dict[prefix + "engine"] = bytearray(self.engine.serialize())
TypeError: 'NoneType' object is not iterable
段错误 (核心已转储)
####
Can you help me?

**Comment by haotian-liu** [comment]
Did you install the TensorRT and PyTorch with the version in [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md)? If not, what is the version you are using? Can you try running without TensorRT (`--disable_tensorrt`) and use FP16 only (`--use_fp16_tensorrt`)?

**Comment by weiluonika** [comment]
> Did you install the TensorRT and PyTorch with the version in [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md)? If not, what is the version you are using? Can you try running without TensorRT (`--disable_tensorrt`) and use FP16 only (`--use_fp16_tensorrt`)?

Yes, I  installed, but for some modules, I didn't follow the [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md) strictly due to Jetson NX (Maybe this is the cause.).  Some modules have been installed with the JetPack4.4.1, as follows:
![sc](https://user-images.githubusercontent.com/50006064/106450517-3e7fe680-64c0-11eb-89f9-f3f848d06262.jpg)


When I try to run without  TensorRT (`--disable_tensorrt`) or use FP16 only (`--use_fp16_tensorrt`), all things are OK but one error: 
#######
$ python3 eval.py --disable_tensorrt --trained_model=./weights/yolact_edge_54_800000.pth
Config not specified. Parsed yolact_edge_config from the file name.

loading annotations into memory...
Done (t=1.35s)
creating index...
index created!
[02/01 16:59:11 yolact.eval]: Loading model...
[02/01 16:59:19 yolact.eval]: Model loaded.

Processing Images  ██████████████████████████████   4952 /   4952 (100.00%)     1.86 fps        
Saving data...
[02/01 17:44:18 yolact.eval]: Calculating mAP...
[02/01 17:44:50 yolact.eval]: 
       |  all  |  .50  |  .55  |  .60  |  .65  |  .70  |  .75  |  .80  |  .85  |  .90  |  .95  |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
   box | 31.92 | 51.90 | 49.68 | 46.80 | 43.39 | 39.47 | 34.08 | 27.17 | 18.04 |  7.82 |  0.85 |
  mask | 29.59 | 47.78 | 45.46 | 42.78 | 39.51 | 35.57 | 31.11 | 25.21 | 17.86 |  9.06 |  1.60 |
-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
Segmentation fault (core dumped)
#######

**Comment by haotian-liu** [comment]
You provided the log for `--disable_tensorrt`, and please confirm it is working for FP16 with `--use_fp16_tensorrt`. If this is the case, could you try calibrating INT8 with less images with `cfg.torch2trt_max_calibration_images` (e.g. set to 5).

**Comment by weiluonika** [comment]
> You provided the log for `--disable_tensorrt`, and please confirm it is working for FP16 with `--use_fp16_tensorrt`. If this is the case, could you try calibrating INT8 with less images with `cfg.torch2trt_max_calibration_images` (e.g. set to 5).

It works after setting `cfg.torch2trt_max_calibration_images` to 5, no more `Segmentation fault (core dumped)` error. But for 10, the error occurs again, which is interesting. Anyway, it works, thanks for your patience. 

For NX, I get around 13~14 fps using `yolact_edge_mobilenetv2_54_800000.pth`, which is incredible. However,  taking into the hardware differences between NX and Xavier, the fps is supposed to being higher, I guess. Is there any setting to achieve this? Thanks.

**Comment by haotian-liu** [comment]
I took a look at [this website](https://www.cnx-software.com/2020/05/16/nvidia-jetson-developer-kits-comparison-nano-vs-tx2-vs-xavier-nx-vs-agx-xavier/) about the NX and AGX comparison.

It seems that NX has less RAM as well as CPU/GPU cores than AGX. The former might account for your previous OOM issue on calibration with `cfg.torch2trt_max_calibration_images=100` but runs fine with five-image calibration.
The latter might suggests why it has inferior FPS than what we have on paper (correct me if the observation is wrong, thanks).

Btw, how do you measure the FPS, using `--benchmark` or using a video?
