### ISSUE TITLE
PR inquiry 

### ISSUE THREAD

**Issue by simutisernestas** [haotian-liu/yolact_edge#48]
Would you be willing to accept a PR for making this installable as a standard python package? We are considering adopting the model to [navigation2_dynamic](https://github.com/ros-planning/navigation2_dynamic) package. But make it work with ROS (or other external systems) is really hard right now. This would include:
 - Packaging for manual install (e.g. ```pip install .```)
 - Adapting internal imports (pkg name prefix)
 - Additional class to import the model with programmatic configuration
 - Maybe some refactoring of the existing code base related to this
 
 Thanks!

**Comment by SteveMacenski** [comment]
The main goal is to make installation easy using the typical python3 tooling. This work wouldn't be ROS-specific, but would let us build out ROS wrappers for this for the purposes of dynamic obstacle avoidance within ROS.

**Comment by haotian-liu** [comment]
Thanks for your interest and support! As long as the performance of the YolactEdge is the same as what we report in the paper, we are very willing to make the installation easy and painless, thus allowing more users to use it.
