### ISSUE TITLE
 "No such file or directory:'./data/coco/annotations/instances_train2017.json' 

### ISSUE THREAD

**Issue by tongxiaozhong14** [haotian-liu/yolact_edge#5]
Dear author, thank you very much for sharing, but when I used your model to detect the video, the question "No such file or directory:'./data/coco/annotations/instances_train2017.json' also appeared. May I ask Which command can be executed to complete the task of video instance segmentation without TensorRT?

**Comment by haotian-liu** [comment]
You can create a new config with TensorRT disabled and evaluate with that. And we will update the script later to support disabling TensorRT with command line options.

For example:

```python
yolact_edge_config.copy({
    'name': ...,

    'torch2trt_backbone': False,
    'torch2trt_backbone_int8': False,
    'torch2trt_protonet': False,
    'torch2trt_protonet_int8': False,
    'torch2trt_fpn': False,
    'torch2trt_fpn_int8': False,
    'torch2trt_prediction_module': False,
    'torch2trt_prediction_module_int8': False,
    'torch2trt_spa': False,
    'torch2trt_spa_int8': False,
    'torch2trt_flow_net': False,
    'torch2trt_flow_net_int8': False,
})
```

**Comment by haotian-liu** [comment]
Please refer to updated documentation in ea3b303.
