### ISSUE TITLE
Custom YOLACT model trains well but shows IndexError in case of eval.py

### ISSUE THREAD

**Issue by ravijo** [haotian-liu/yolact_edge#51]
Hi,

Thank you for developing this amazing tool.

I recently modified the [yolact.py](https://github.com/haotian-liu/yolact_edge/blob/master/yolact.py) and added one more mask so that the network predicts 2 of them (instead of 1). I am also using a custom dataset. The training works fine but [eval.py](https://github.com/dbolya/yolact/blob/master/eval.py) is showing the following error:
```
File "eval.py", line 173, in prep_display
    masks = t[3][idx]
IndexError: too many indices for tensor of dimension 3
```

I checked the size of `idx` and `t[3]` to debug the issue and found the following information:
```
idx: tensor([0, 1, 2, 3, 4])
idx.size(): torch.Size([5])
t[3].size(): torch.Size([100, 480, 640])
```
It seems that the error is misleading. Anyway, after a while, I realized that in your [eval.py](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/eval.py#L173), the variable `idx` is simply `:args.top_k`. So I changed it but then the output from `eval.py` was shown incorrectly.

Moreover, the statement `masks = t[3][idx]` works fine if [PredictionModuleTRTWrapper](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L1631-L1632) is disabled (just comment 2 lines). I should also mention that the network shows the above error in forward propagation step in `eval.py`. This leads me to think that the `pred_layer` is not set properly. 

Can you please help me out? Is [input_sizes](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L560) variable is set properly or needs some modification?

Thank you so much.

**Comment by haotian-liu** [comment]
There might be a weird issue with the TensorRT engine or torch2trt, and there are similar issues related to this. I have found a workaround by using `torch.index_select`.

Can you try replacing this line with the following to see if the error persists:

```python
masks = torch.index_select(t[3], 0, idx)
```

**Comment by ravijo** [comment]
Thank you so much, @haotian-liu

The `IndexError` is gone now. Thank you again.

However, I see the following warning:
```
Encountered IndexError as mentioned in https://github.com/haotian-liu/yolact_edge/issues/27.
Flattening predictions to avoid error, please verify the outputs.
If there are any problems you met related to this, please report an issue.
```
Furthermore, the output image is not shown as expected. More precisely, both of the generated masks are overlapping. Again, the output looks fine when [PredictionModuleTRTWrapper](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L1631-L1632) is disabled (just comment 2 lines). Also, in this case, the message `Encountered IndexError as mentioned ...` does not appear.

**Comment by haotian-liu** [comment]
Can you show the two sample images? And also can you explain what you did with `when PredictionModuleTRTWrapper is disabled (just comment 2 lines).` (just show the modification here). Thanks.

**Comment by ravijo** [comment]
Thanks a lot.

The model is a modified version with 2 masks (instead of 1).  That is why you might have noticed that size of `idx` variable was 5 (instead of 4).

`PredictionModuleTRTWrapper` modification is shown below:

[Before]
```
for idx, pred_layer in enumerate(self.prediction_layers):
    pred_layer = PredictionModuleTRTWrapper(pred_layer)
    pred_layer.to_tensorrt(batch_size=batch_size)
    self.prediction_layers[idx] = pred_layer
```
[After]
```
for idx, pred_layer in enumerate(self.prediction_layers):
    # pred_layer = PredictionModuleTRTWrapper(pred_layer)
    # pred_layer.to_tensorrt(batch_size=batch_size)
    self.prediction_layers[idx] = pred_layer
```
The above lines are being called when converting `PredictionModule` to `TensorRT` by executing `eval.py`. Because the conversion is unrelated to training, so training works fine. Please note that only the `PredictionModule` conversion is showing the error. Rest I already managed.

Regarding the `Encountered IndexError as mentioned ...` warning, I printed the shape of tensors. Please see below:
```
print('classes:', type(classes), classes.size())
print('keep:', type(keep), keep.size())
classes = classes[keep]
boxes = boxes[keep]

# Below is the output of the above print statements
classes: <class 'torch.Tensor'> torch.Size([12, 148])
keep: <class 'torch.Tensor'> torch.Size([12, 148])
```

As you suggested previously, I thought `classes = torch.index_select(classes, 0, keep)` would be a good idea but it turned out the variable `keep` must be a [vector](https://pytorch.org/docs/stable/generated/torch.index_select.html).
```
classes = torch.index_select(classes, 0, keep)
RuntimeError: Index is supposed to be an empty tensor or a vector
```



Again, please note that the `Encountered IndexError as mentioned ...` warning doesn't appear when `PredictionModuleTRTWrapper` is disabled and output is perfect too.

**Comment by ravijo** [comment]
Because the error is coming from `pred_layer`, so I added some print statements to check the shape of the tensor given to `pred_layer` inside `yolact.py`. Please see below:

```
# a print statement is added at Line 569
x = torch.ones(input_sizes[self.pred_layer.index]).cuda()
self.pred_layer_torch = self.pred_layer
print('yolact.py L569', x.size())
self.pred_layer = trt_fn(self.pred_layer, [x])

# a print statement is added at Line 576
print('yolact.py L576', x.size())
bbox, conf, mask, my_mask = self.pred_layer(x)
priors = self.pred_layer_torch.make_priors(conv_h, conv_w)

# a print statement is added at Line 969
for pred_layer in self.pred_layers:
    j -= 1
    print('yolact.py L969', out[j].size())
    out[j] = F.relu(pred_layer(out[j]))

# a print statement is added at Line 1816
print('yolact.py L1816', x.size())
p = pred_layer(pred_x)

for k, v in p.items():
    pred_outs[k].append(v)
```

Below is the output during training the network. (Please note that only unique print statements are shown rest are removed to make this post shorter):
```
yolact.py L969 torch.Size([4, 256, 18, 18])
yolact.py L969 torch.Size([4, 256, 35, 35])
yolact.py L969 torch.Size([4, 256, 69, 69])
yolact.py L1816 torch.Size([4, 3, 550, 550])
```

Below is the output during the evaluation of the network when `PredictionModuleTRTWrapper` is commented. In this case, `PredictionModuleTRTWrapper` is not used and the output is perfect. (Please note that only unique print statements are shown rest are removed to make this post shorter):
```
Converting PredictionModule to TensorRT...
Converted to TensorRT.
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L1816 torch.Size([1, 3, 550, 550])
```

Below is the output during the evaluation of the network when `PredictionModuleTRTWrapper` is not commented. In this case, `PredictionModuleTRTWrapper` is used and the output is incorrect (two masks are overlapping). (Please note that only unique print statements are shown rest are removed to make this post shorter):
```
Converting PredictionModule to TensorRT...
yolact.py L569 torch.Size([1, 256, 69, 69])
yolact.py L569 torch.Size([1, 256, 35, 35])
yolact.py L569 torch.Size([1, 256, 18, 18])
yolact.py L569 torch.Size([1, 256, 9, 9])
yolact.py L569 torch.Size([1, 256, 5, 5])
Converted to TensorRT.
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L576 torch.Size([1, 256, 69, 69])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L576 torch.Size([1, 256, 35, 35])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L576 torch.Size([1, 256, 18, 18])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L576 torch.Size([1, 256, 9, 9])
yolact.py L1816 torch.Size([1, 3, 550, 550])
yolact.py L576 torch.Size([1, 256, 5, 5])
```

**Comment by haotian-liu** [comment]
The problem seems related to TensorRT engine or torch2trt according to my previous observations. Here is how I made this claim: with TensorRT [on/off] I stored all of the predicted outputs of the PredictionModule to a pickle file, restart the program with TensorRT [on/off], load the pickled file and run the postprocessing steps.

In your case, [on, on] causes the problem, which is also reported by some of the users. What I observe later is that [on, off] does not have the issue (IndexError). This makes me think that TensorRT engine/torch2trt "corrupts" the PyTorch engine on some executions. I am still investigating why and is not sure if this is a bug of the TensorRT or torch2trt. I plan to report to both TensorRT and torch2trt later this month, but not sure how soon we will have the reply and fix. Also, this observation also explains why disabling TensorRT conversion will eliminate this error.

Currently the latest commit (updated recently, so you might not be on it if you pull the repo much earlier so you might want to double check) contains my current workaround: if such IndexError happens, use `torch.index_select` instead, and if `keep` is not a vector, we will flatten both the source and the index tensor to a vector, and use the index_select on `dim=0`.

**Comment by ravijo** [comment]
Thank you so much @haotian-liu 

May I request you to share the version of `TensorRT` and `torch2trt` of your environment? I am thinking to downgrade `torch2trt` as it could be a possible culprit.

Well, I am going to follow your suggestion and report to you the status soon. Meanwhile, I am sharing my environment information (which I should have shared in the beginning). Please see below:

#### Device Name
```
NVIDIA Jetson AGX Xavier [16GB] - JetPack 4.5 [L4T 32.5.0] 
# the above information is shown by jtop
```

#### Package nvinfer Info.
```
$ dpkg -l | grep nvinfer
ii  libnvinfer-bin                7.1.3-1+cuda10.2        arm64        TensorRT binaries
ii  libnvinfer-dev                7.1.3-1+cuda10.2        arm64        TensorRT development libraries and headers
ii  libnvinfer-doc                7.1.3-1+cuda10.2        all          TensorRT documentation
ii  libnvinfer-plugin-dev         7.1.3-1+cuda10.2        arm64        TensorRT plugin libraries
ii  libnvinfer-plugin7            7.1.3-1+cuda10.2        arm64        TensorRT plugin libraries
ii  libnvinfer-samples            7.1.3-1+cuda10.2        all          TensorRT samples
ii  libnvinfer7                   7.1.3-1+cuda10.2        arm64        TensorRT runtime libraries
ii  python-libnvinfer             7.1.3-1+cuda10.2        arm64        Python bindings for TensorRT
ii  python-libnvinfer-dev         7.1.3-1+cuda10.2        arm64        Python development package for TensorRT
ii  python3-libnvinfer            7.1.3-1+cuda10.2        arm64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev        7.1.3-1+cuda10.2        arm64        Python 3 development package for TensorRT
```

#### Package TensorRT Info.
```
$ dpkg -l | grep TensorRT
ii  graphsurgeon-tf                       7.1.3-1+cuda10.2          arm64        GraphSurgeon for TensorRT package
ii  libnvinfer-bin                        7.1.3-1+cuda10.2          arm64        TensorRT binaries
ii  libnvinfer-dev                        7.1.3-1+cuda10.2          arm64        TensorRT development libraries and headers
ii  libnvinfer-doc                        7.1.3-1+cuda10.2          all          TensorRT documentation
ii  libnvinfer-plugin-dev                 7.1.3-1+cuda10.2          arm64        TensorRT plugin libraries
ii  libnvinfer-plugin7                    7.1.3-1+cuda10.2          arm64        TensorRT plugin libraries
ii  libnvinfer-samples                    7.1.3-1+cuda10.2          all          TensorRT samples
ii  libnvinfer7                           7.1.3-1+cuda10.2          arm64        TensorRT runtime libraries
ii  libnvonnxparsers-dev                  7.1.3-1+cuda10.2          arm64        TensorRT ONNX libraries
ii  libnvonnxparsers7                     7.1.3-1+cuda10.2          arm64        TensorRT ONNX libraries
ii  libnvparsers-dev                      7.1.3-1+cuda10.2          arm64        TensorRT parsers libraries
ii  libnvparsers7                         7.1.3-1+cuda10.2          arm64        TensorRT parsers libraries
ii  nvidia-container-csv-tensorrt         7.1.3.0-1+cuda10.2        arm64        Jetpack TensorRT CSV file
ii  python-libnvinfer                     7.1.3-1+cuda10.2          arm64        Python bindings for TensorRT
ii  python-libnvinfer-dev                 7.1.3-1+cuda10.2          arm64        Python development package for TensorRT
ii  python3-libnvinfer                    7.1.3-1+cuda10.2          arm64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev                7.1.3-1+cuda10.2          arm64        Python 3 development package for TensorRT
ii  tensorrt                              7.1.3.0-1+cuda10.2        arm64        Meta package of TensorRT
ii  uff-converter-tf                      7.1.3-1+cuda10.2          arm64        UFF converter for TensorRT package
```

#### Package torch2trt Info.
```
$ ipython
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch2trt

In [2]: torch2trt.__package__
Out[2]: 'torch2trt'

In [3]: torch2trt.__spec__
Out[3]: ModuleSpec(name='torch2trt', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f8307feb8>, origin='/home/ravi/my_env/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt/__init__.py', submodule_search_locations=['/home/ravi/my_env/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt'])

In [4]: torch2trt.__path__
Out[4]: ['/home/ravi/my_env/lib/python3.6/site-packages/torch2trt-0.1.0-py3.6-linux-aarch64.egg/torch2trt']

In [7]: torch2trt.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e35dd0616379> in <module>
----> 1 torch2trt.__version__

AttributeError: module 'torch2trt' has no attribute '__version__'
```

#### nv_tegra_release Info.
 ```
$ cat /etc/nv_tegra_release
# R32 (release), REVISION: 5.0, GCID: 25531747, BOARD: t186ref, EABI: aarch64, DATE: Fri Jan 15 23:21:05 UTC 2021
```

#### Package nvidia-jetpack Info.
```
$ apt-cache show nvidia-jetpack
Package: nvidia-jetpack
Version: 4.5-b129
Architecture: arm64
Maintainer: NVIDIA Corporation
Installed-Size: 194
Depends: nvidia-cuda (= 4.5-b129), nvidia-opencv (= 4.5-b129), nvidia-cudnn8 (= 4.5-b129), nvidia-tensorrt (= 4.5-b129), nvidia-visionworks (= 4.5-b129), nvidia-container (= 4.5-b129), nvidia-vpi (= 4.5-b129), nvidia-l4t-jetson-multimedia-api (>> 32.5-0), nvidia-l4t-jetson-multimedia-api (<< 32.6-0)
Homepage: http://developer.nvidia.com/jetson
Priority: standard
Section: metapackages
Filename: pool/main/n/nvidia-jetpack/nvidia-jetpack_4.5-b129_arm64.deb
Size: 29360
SHA256: 002646e6d81d13526ade23d7c45180014f3cd9e9f5fb0f8896b77dff85d6b9fe
SHA1: cb17547b902b2793e0df86d561809ecdbf7e401f
MD5sum: 06962c42e462f643455d6194d1a2d641
Description: NVIDIA Jetpack Meta Package
Description-md5: ad1462289bdbc54909ae109d1d32c0a8
```

[The installation manual says](https://github.com/haotian-liu/yolact_edge/blob/73c42b8e2789d9660002c0fb67a974ce67230720/INSTALL.md) to install TensorRT v7.1.3.4 and torch2trt v0.1.0. Can you please confirm the version of `TensorRT` and `torch2trt` of your environment?

**Comment by ravijo** [comment]
Hello @haotian-liu 

I checked and found that I am using the latest commit. Because I could see `torch.index_select`. I am still trying to debug the issue. I added a few print statements as shown below:

```
def flatten_index_select(x, idx, end_dim=None):
    x = torch.flatten(x, end_dim=end_dim)
    return torch.index_select(x, 0, idx)

try:
    print('keep:', type(keep), keep.size())
    print('classes:', type(classes), classes.size())
    classes = classes[keep]
    boxes = boxes[keep]
    masks = masks[keep]
    masks_secondary = masks_secondary[keep]
    scores = scores[keep]
except IndexError as e:
    print('[IndexError] L185', e)
    from utils.logging_helper import log_once
```

Below is the output:
```
keep: <class 'torch.Tensor'> torch.Size([12, 90])
classes: <class 'torch.Tensor'> torch.Size([12, 90])
[IndexError] L185 too many indices for tensor of dimension 2
```
The dimensions of each tensor are not changing even if `PredictionModuleTRTWrapper` is not used. But when `PredictionModuleTRTWrapper` is not used, the above slicing works without throwing any exception. The behavior is looking strange to me!

**Comment by haotian-liu** [comment]
This is exactly what I found, and that is why I thought it was an TensorRT/PyTorch engine issue.

**Comment by ravijo** [comment]
I just verified that when `PredictionModuleTRTWrapper` is used, both masks are indeed same.I used following statement to check two tensors:

```
print('Equal:', torch.all(mask_a.eq(mask_b)))
```

The above returns `true` when `PredictionModuleTRTWrapper` is used and `false` when `PredictionModuleTRTWrapper` is not used.

Request
------------
I shared my environment info [here](https://github.com/haotian-liu/yolact_edge/issues/51#issuecomment-780299027). The [installation manual](https://github.com/haotian-liu/yolact_edge/blob/73c42b8e2789d9660002c0fb67a974ce67230720/INSTALL.md) says to install TensorRT v7.1.3.4 and torch2trt v0.1.0. Can you please confirm the version of TensorRT and torch2trt of your environment?

**Comment by haotian-liu** [comment]
Yes the environment is the same. I am confused about mask_a and mask_b: how are they generated, how they are dependent of each other, what are the relationship between them?

**Comment by ravijo** [comment]
The network structure is almost similar. Please see below the different part of the network:

```
  (prediction_layers): ModuleList(
    (0): PredictionModule(
      (upfeature): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): ReLU(inplace=True)
      )
      (bbox_layer): Conv2d(256, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conf_layer): Conv2d(256, 39, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_a_layer): Conv2d(256, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (mask_b_layer): Conv2d(256, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (1): PredictionModule()
    (2): PredictionModule()
    (3): PredictionModule()
    (4): PredictionModule()
  )
  (semantic_seg_a_conv): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
  (semantic_seg_b_conv): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
)
```

I checked with the previous 5 commits of torch2trt, TensorRT v77.1.3, and TensorRT v7.2.2 but no luck :cry: 

Can you point me to a better way to debug the issue?

**Comment by haotian-liu** [comment]
So you modified mask layer of the PredictionModule, did you also do the same thing for PredictionModuleTRT?

**Comment by ravijo** [comment]
> So you modified mask layer of the PredictionModule, did you also do the same thing for PredictionModuleTRT?

Yes. I did.

I added a few `print(torch.equal(mask_a, mask_b))` statements. Please see below my additional findings:

* When `PredictionModuleTRTWrapper` is disabled, the `print` statement says `False` at [L256](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L256)
* When  `PredictionModuleTRTWrapper` is enabled, the `print` statement at [L256](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L256) doesn't get executed. However, the  `print` statement at [L375](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L375) says `True`. This is why the output is looking incorrect because two masks are overallaping/same.

It seems that `PredictionModuleTRT` is optimizing something ??? :confused:

**Comment by haotian-liu** [comment]
What if you only disable the tensorrt conversion?

```python
for idx, pred_layer in enumerate(self.prediction_layers):
    pred_layer = PredictionModuleTRTWrapper(pred_layer)
    # pred_layer.to_tensorrt(batch_size=batch_size)
    self.prediction_layers[idx] = pred_layer
```

**Comment by ravijo** [comment]
There was a mistake and I just realized it. I accidentally used the same layer at [L352](https://github.com/haotian-liu/yolact_edge/blob/11840512ab46f22dce6aea37a7823110175adffa/yolact.py#L352) for both the masks.

It works fine. The `IndexError` is cached by `torch.index_select`.

Thank you so much!

**Comment by ravijo** [comment]
torch.index_select

**Comment by haotian-liu** [comment]
Cool, if everything works fine, I will be closing this issue for now. Please feel free to reopen if there are more questions.
