### ISSUE TITLE
Getting 27.8 FPS instead of 30.7 on Xavier AGX

### ISSUE THREAD

**Issue by dbtmpl** [haotian-liu/yolact_edge#56]
Hi, 

First, thanks a lot for the project. Great work!

I want to double-check what configs/setup you used for achieving the reported `30.7` FPS.

The steps I take are simple: 
1. I clone the repo
2. Download the COCO ResNet-50 model (`yolact_edge_resnet50_54_800000.pth`)
2. Download the calibration images and add COCO validation images
3. Put the AGX on `MAXN` mode 
4. Run the benchmark script with the default configs
```
python eval.py --trained_model=weights/yolact_edge_resnet50_54_800000.pth --benchmark --max_images=1000
``` 
I get `27.82` FPS and `35.94` ms on average.

Any default settings I have to change to optimize the FPS?

**Comment by rrivera1849** [comment]
Try running it in the background on all images as follows:

```python
python eval.py --benchmark --trained_model=./weights/yolact_edge_resnet50_54_800000.pth > out 2>&1 &
```

This is the output I get:

    Average: 31.32 fps, 31.93 ms

**Comment by dbtmpl** [comment]
Interesting, running it in the background I am getting:

```
Average: 29.36 fps, 34.06 ms
```

These are the inference times in the network:
```
      Name      | Time (ms)  
----------------+------------
  Network Extra |     0.6145 
       backbone |     1.6271 
            fpn |     1.7731 
          proto |     0.7689 
     pred_heads |     2.8692 
     makepriors |     0.0227 
         Detect |    21.5822 
    Postprocess |     1.6205 
           Sync |     0.0983 
----------------+------------
          Total |    30.9765 
```

**Comment by dbtmpl** [comment]
This run was on all. But I see roughly the same average FPS when I only use the first 1000. 

Do you execute something like ```sudo jetson_clocks``` before?

**Comment by rrivera1849** [comment]
No, we don't overclock the Xavier before running it although that will likely get it to the 30fps for you. Let me think of other environmental differences.

**Comment by haotian-liu** [comment]
If you plugged in your Xavier to an monitor, the GPU on Xavier uses part of its resources for rendering (and this consumes different amount depending on the applications you are running). We evaluated using SSH remote connection, and got ~31 FPS.

**Comment by dbtmpl** [comment]
That makes a lot of sense, thanks a bunch for the clarifications. Right now I'm happy with the performance I'm getting, but it's good to know how to squeeze out the last few percentages. From my book we can close this issue.
