### ISSUE TITLE
Ignoring ImageIDs without annotations and images

### ISSUE THREAD

**Issue by cyrilzakka** [haotian-liu/yolact_edge#60]
Is there a way to ignore image IDs without images or annotations? I merged datasets using https://pypi.org/project/coco-assistant/ and deleted all images without annotations but I realize they stayed inside the annotation files and it raises the following error: 

```
assert osp.exists(path), 'Image path does not exist: {}'.format(path)
AssertionError: Image path does not exist: /content/yolact_edge/data/coco/images/frame_003476.PNG
```

**Comment by haotian-liu** [comment]
You can simply remove them from the annotation file.

**Comment by cyrilzakka** [comment]
I have over 10K of those but I'll give it a go.

**Comment by cyrilzakka** [comment]
This is how I fixed it in `coco.py`:
```
        self.tempIds = []
        for index in range(len(self.ids)):
            img_id = self.ids[index]
            file_name = self.coco.loadImgs(img_id)[0]['file_name']
            path = osp.join(self.root, file_name)
            if osp.exists(path):
                self.tempIds.append(img_id)
```
