### ISSUE TITLE
Even after TensorRT conversion, loading weights from .pth file is surprisingly necessary

### ISSUE THREAD

**Issue by ravijo** [haotian-liu/yolact_edge#62]
Hi,

Thank you for developing this amazing tool. 

Normally, a model once converted to TensorRT just need to load the weights from a `trt` file. However, in the case of `yolact_edge`, I see that weights are loaded twice. 

First, the `pth` file is loaded as shown below:

https://github.com/haotian-liu/yolact_edge/blob/3aa5e39db1ed1a057baf79c2e1a74debc7ee83d8/eval.py#L1235

And then each module, such as backbone, etc are loaded as shown below:

https://github.com/haotian-liu/yolact_edge/blob/3aa5e39db1ed1a057baf79c2e1a74debc7ee83d8/yolact.py#L1552

[By taking a reference from here](https://github.com/NVIDIA-AI-IOT/torch2trt#save-and-load), I verified and found that a TensorRT module does not need to be loaded twice. 

**Therefore, to speed up initialization, the `yolact_edge` should not require to load `.pth` file when all `trt` files are present.**

To this end, I saved and compared the `state_dict` of the model for the following two cases:
1. When initially weights are loaded from a `pth` file
2. When only converted `trt` weights were loaded

### Observation
* Both the weight files have equal 72 keys 
* However some keys have different values. Please see the below table:

| Key| Value| Max Difference| Data Type| 
|--- |--- | ---| ---|
| backbone.engine| same| | | 
| backbone.input_names| same| | | 
| backbone.output_names| same| | | 
| proto_net.engine| same| | | 
| proto_net.input_names| same| | | 
| proto_net.output_names| same| | | 
| fpn_phase_1.engine| same| | | 
| fpn_phase_1.input_names| same| | | 
| fpn_phase_1.output_names| same| | | 
| fpn_phase_2.engine| same| | | 
| fpn_phase_2.input_names| same| | | 
| fpn_phase_2.output_names| same| | | 
| prediction_layers.0.pred_layer.engine| mismatch| | bytearray| 
| prediction_layers.0.pred_layer.input_names| same| | | 
| prediction_layers.0.pred_layer.output_names| same| | | 
| prediction_layers.0.pred_layer_torch.upfeature.0.weight| mismatch| 0.3143| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.upfeature.0.bias| mismatch| 0.4897| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.bbox_layer.weight| mismatch| 0.7085| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.bbox_layer.bias| mismatch| 0.504| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.conf_layer.weight| mismatch| 0.56| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.conf_layer.bias| mismatch| 2.0304| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.mask_layer.weight| mismatch| 0.2454| torch.Tensor | 
| prediction_layers.0.pred_layer_torch.mask_layer.bias| mismatch| 0.2326| torch.Tensor | 
| prediction_layers.1.pred_layer.engine| mismatch| | bytearray| 
| prediction_layers.1.pred_layer.input_names| same| | | 
| prediction_layers.1.pred_layer.output_names| same| | | 
| prediction_layers.1.pred_layer_torch.upfeature.0.weight| mismatch| 0.3143| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.upfeature.0.bias| mismatch| 0.4897| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.bbox_layer.weight| mismatch| 0.7085| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.bbox_layer.bias| mismatch| 0.504| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.conf_layer.weight| mismatch| 0.56| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.conf_layer.bias| mismatch| 2.0304| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.mask_layer.weight| mismatch| 0.2454| torch.Tensor | 
| prediction_layers.1.pred_layer_torch.mask_layer.bias| mismatch| 0.2326| torch.Tensor | 
| prediction_layers.2.pred_layer.engine| mismatch| | bytearray| 
| prediction_layers.2.pred_layer.input_names| same| | | 
| prediction_layers.2.pred_layer.output_names| same| | | 
| prediction_layers.2.pred_layer_torch.upfeature.0.weight| mismatch| 0.3143| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.upfeature.0.bias| mismatch| 0.4897| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.bbox_layer.weight| mismatch| 0.7085| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.bbox_layer.bias| mismatch| 0.504| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.conf_layer.weight| mismatch| 0.56| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.conf_layer.bias| mismatch| 2.0304| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.mask_layer.weight| mismatch| 0.2454| torch.Tensor | 
| prediction_layers.2.pred_layer_torch.mask_layer.bias| mismatch| 0.2326| torch.Tensor | 
| prediction_layers.3.pred_layer.engine| mismatch| | bytearray| 
| prediction_layers.3.pred_layer.input_names| same| | | 
| prediction_layers.3.pred_layer.output_names| same| | | 
| prediction_layers.3.pred_layer_torch.upfeature.0.weight| mismatch| 0.3143| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.upfeature.0.bias| mismatch| 0.4897| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.bbox_layer.weight| mismatch| 0.7085| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.bbox_layer.bias| mismatch| 0.504| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.conf_layer.weight| mismatch| 0.56| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.conf_layer.bias| mismatch| 2.0304| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.mask_layer.weight| mismatch| 0.2454| torch.Tensor | 
| prediction_layers.3.pred_layer_torch.mask_layer.bias| mismatch| 0.2326| torch.Tensor | 
| prediction_layers.4.pred_layer.engine| mismatch| | bytearray| 
| prediction_layers.4.pred_layer.input_names| same| | | 
| prediction_layers.4.pred_layer.output_names| same| | | 
| prediction_layers.4.pred_layer_torch.upfeature.0.weight| mismatch| 0.3143| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.upfeature.0.bias| mismatch| 0.4897| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.bbox_layer.weight| mismatch| 0.7085| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.bbox_layer.bias| mismatch| 0.504| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.conf_layer.weight| mismatch| 0.56| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.conf_layer.bias| mismatch| 2.0304| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.mask_layer.weight| mismatch| 0.2454| torch.Tensor | 
| prediction_layers.4.pred_layer_torch.mask_layer.bias| mismatch| 0.2326| torch.Tensor | 
| semantic_seg_conv.weight| mismatch| 0.5225| torch.Tensor | 
| semantic_seg_conv.bias| mismatch| 0.1992| torch.Tensor | 
| lat_layer.engine| same| | | 
| lat_layer.input_names| same| | | 
| lat_layer.output_names| same| | | 

Here, max difference is nothing but simply `torch.max( torch.abs( val_1 - val_2 ) )`

It seems that only `prediction_layers` and `semantic_seg_conv` layers are mismatching. 

Furthermore, **`yolact_edge` is not segmenting anything if only `trt` weights are loaded but initial weights are not loaded from `pth` file.**

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our project. For your questions:

(1) It is true that in the cases where all the model weights have been compiled to TensorRT cache, you can skip the weight loading of the original model. We currectly do not plan to do this simply because that this does not take a long time, and doing this might create some unforseen outcomes; trading-off between them, we at this point do not see a very good reason for us to do so.

(2) If you take a careful look at the parameters you are printing, you will see that the "same" parameters are all "engine", "input_names", "output_names", and the mismatch parameters are simply those without TensorRT counterparts (not converted to TensorRT).

**Comment by ravijo** [comment]
Hi @haotian-liu 

> (1) It is true that in the cases where all the model weights have been compiled to TensorRT cache, you can skip the weight loading of the original model.

If I skip the weight loading of the original model. it doesn't seem to produce correct results. Please see below:

First, please comment following lines in [eval.py#L1234-L1237](https://github.com/haotian-liu/yolact_edge/blob/3aa5e39db1ed1a057baf79c2e1a74debc7ee83d8/eval.py#L1234-L1237):

https://github.com/haotian-liu/yolact_edge/blob/3aa5e39db1ed1a057baf79c2e1a74debc7ee83d8/eval.py#L1234-L1237

```
python3 eval.py --trained_model=./weights/yolact_edge_54_800000.pth --image=dog.jpg --score_threshold 0.3
```

![incorrect](https://user-images.githubusercontent.com/1439011/109125877-f175f400-778f-11eb-8e09-907e576ff9cf.png)


Correct result:
```
python3 eval.py --trained_model=./weights/yolact_edge_54_800000.pth --image=dog.jpg --score_threshold 0.3
```

![correct](https://user-images.githubusercontent.com/1439011/109125896-f76bd500-778f-11eb-8ab9-57f321143709.png)

The input image can be downloaded from [here](https://learnopencv.com/wp-content/uploads/2019/05/dog.jpg).

This leads me to think that model weights are not loaded correctly?

**Comment by haotian-liu** [comment]
Not all the modules are **fully cached**. You can try not loading the backbone weights, and it shall work.

**Comment by ravijo** [comment]
Sorry, you mean load `pth` first but do not load backbone `trt` weights? This approach works. But I was trying to skip loading `pth` file.

Is there any way to fully cache backbone weights?

**Comment by haotian-liu** [comment]
You can skip loading all the module weights if they are cached, and only loading the rest. You can create a new pth file containing only those weights.

**Comment by ravijo** [comment]
Sorry, I think both of us are on different page.

I want to use TensorRT so I can not skip loading `trt` weights. Since all of the modules are already converted to TensorRT, I thought that there should be no need to load `pth` file. However, you just mentioned that some of the modules are not fully cached.

Can you please explain the process you just mentioned above?

**Comment by haotian-liu** [comment]
Could you explain a bit more on: (1) which step you want to avoid, loading pth or trt? (2) and why.

**Comment by ravijo** [comment]
> Could you explain a bit more on: (1) which step you want to avoid, loading pth or trt?

`pth` file.

> why.

Because the model is already converted to and saved to `trt`. So we should be able to load `trt` and do inference directly _(but you said some modules aren't fully cached so only loading `trt` will not work. But in theory `TRTModule` works just by loading weights from `trt` file)_

**Comment by ravijo** [comment]
> (1) It is true that in the cases where all the model weights have been compiled to TensorRT cache, you can skip the weight loading of the original model. 

Yeah. the original weight file `yolact_edge_54_800000.pth` is having 662 keys, i.e., `len(state_dict.keys())`. So there is no way to skip loading of `pth` file. The cached `trt` files aren't the full cache as you said.

**Comment by haotian-liu** [comment]
You can skip the loading actually. The reason you cannot see the full state dictionary in trt cached model is that it has already been quantized, but the TRT model itself is functional.
Currently PredictionModule is not fully cached, and we could later make it fully cached. If you want to avoid loading most of the pth files, you can create a smaller pth file that does not contain the backbone/protonet/fpn weights, and load it instead.
