### ISSUE TITLE
Warning: Moving average ignored a value of nan/inf

### ISSUE THREAD

**Issue by ChaofanTao** [haotian-liu/yolact_edge#63]
Hi,

I use the following command to train yolact_edge on COCO-2017 dataset
```python
 python train.py --config=yolact_edge_config --dataset coco2017_dataset
```

after training normally for a few iterations, I get the log like that
```

[03/03 20:01:13 yolact.train]: eta: 2 days, 16:03:49  epoch: 0  iter: 2310  B: 4553196547360513069834586017497088.000  M: 7.165  C: 1973261171199612081599711933366272.000  S: 53
.717  T: 6526457718560124863203921799151616.000  time: 1.050  data_time: 0.634  lr: 0.004000  max_mem: 8498M
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan

```

What is the possible reason and solution for this? Thank you very much !

PS: I set ```--num_workers``` as 0 in ```train.py``` because I get "RuntimeError: DataLoader worker (pid 16560) is killed by signal: Killed" when using the default argument ```--num_workers``` as 4, followed by [link](https://github.com/facebookresearch/maskrcnn-benchmark/issues/195).

**Comment by haotian-liu** [comment]
What is the batch size you are using, and how many GPUs you used to train? Did you modify any of the configs?

**Comment by ChaofanTao** [comment]
> What is the batch size you are using, and how many GPUs you used to train? Did you modify any of the configs?

I use the default setting: batch size == 8, GPUs = =4, do not change configs. And per GPU memory consumption is  11000MB/32000MB (v100 card). I think the --num_workers just have an effect on the images I/O speed?

**Comment by haotian-liu** [comment]
Were you training using the most up-to-date code? It will help with the NaN/Inf issue. If still not resolved, please try training with a single GPU to see if it resolves the issue. The number_workers should just affect the training speed (you might want to set it to at least 1 or 2 -- or the training speed will be fairly slow).
