### ISSUE TITLE
How to ONNX conver ? 

### ISSUE THREAD

**Issue by KangHoyong** [haotian-liu/yolact_edge#68]
How to ONNX conver ?

**Comment by haotian-liu** [comment]
Currently we use torch2trt to convert the model to TensorRT. You can create your own ONNX converter if you'd like to.

**Comment by MiaoRain** [comment]
> How to ONNX conver ?

Hi， have you got an ONNX conver?

**Comment by zzzz737** [comment]
> > How to ONNX conver ?
> 
> Hi， have you got an ONNX conver?

hello, have you get an onnx file now? i meet some error!
