### ISSUE TITLE
Did anyone train this on cityscape dataset?

### ISSUE THREAD

**Issue by Tetsujinfr** [haotian-liu/yolact_edge#69]
Any results/model avalable on cityscape by any chance?
Licencing challenges?
Thanks a lot

**Comment by haotian-liu** [comment]
We do not experiment on cityscapes, but you might want to take a look at the original YOLACT to see if there is anyone trained that with YOLACT. You can take that model and YolactEdge can automatically convert them.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
