### ISSUE TITLE
Unable to Generate json output with custom dataset

### ISSUE THREAD

**Issue by janandd** [haotian-liu/yolact_edge#71]
I have trained a model on custom dataset with 5 classes. Using `images=/input/folder:output/folder` argument in `evaly.py`, the inference on new images could be obtained. Also, for validation dataset, the detections in json format could be obtained with the `output_coco_json` argument by adding a custom dataset in the `data/config.py` file.
However, I could find no way to generate json file with `images` argument. In this case, only the `evalimages` and `evalimage` function is called which does not generate the json file.
I would be happy if anyone could help me with this problem.

**Comment by rrivera1849** [comment]
Hi there! We just pushed up some code that allows you to save the json file when using --image or --images. 

Here are example commands:

```python
python eval.py --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --images=./test_input:./test_output --output_coco_json --use_tensorrt_safe_mode

python eval.py --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --image=test_image.jpg:test_image_out.jpg --output_coco_json --use_tensorrt_safe_mode
```

**Comment by janandd** [comment]
Thank you very much! Got what I was looking for!
