### ISSUE TITLE
couldn't find any classes

### ISSUE THREAD

**Issue by sinuku** [haotian-liu/yolact_edge#72]
Hi,
I use pretrained model with YOLACT, and image size is 100*100

if I use _yolact_edge_resnet50_config_, couldn't find any classes on `python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.15 --top_k=15 --images=path/to/input/folder:path/to/output/folder`
```
my_yolact_config = yolact_edge_resnet50_config.copy({
    'name': 'my_config',
    'dataset': my_dataset,
    'num_classes': len(my_dataset.class_names) + 1,
    'max_size': 100,
    'backbone': yolact_resnet50_config.backbone.copy({
        'pred_scales': [[4], [8], [16], [32], [64]],
    }),
})
```

but if I use _yolact_base_config_ (without TensorRT), it finds well
```
my_yolact_config = yolact_base_config.copy({
    'name': 'my_config',
    'dataset': my_dataset,
    'num_classes': len(my_dataset.class_names) + 1,
    'max_size': 100,
    'backbone': yolact_resnet50_config.backbone.copy({
        'pred_scales': [[4], [8], [16], [32], [64]],
    }),
})
```

what's the problem??

**Comment by haotian-liu** [comment]
Please see if [this](https://github.com/haotian-liu/yolact_edge#handling-inference-error-when-using-tensorrt) helps.

**Comment by sinuku** [comment]
I tried with `python eval.py --use_fp16_tensorrt --use_tensorrt_safe_mode --config=yolact_edge_config --trained_model=weights/yolact_resnet50_custom_16666_50000.pth --score_threshold=0.3 --top_k=100 --images=~/Desktop/test:output_images`

and I changed `yolact_edge_config`
```
yolact_edge_config = yolact_base_config.copy({
    'name': 'yolact_edge',

    'max_size': 100,

    'torch2trt_max_calibration_images': 100,
    'torch2trt_backbone_int8': True,
    'torch2trt_protonet_int8': True,
    'torch2trt_fpn': True,
    'torch2trt_prediction_module': True,
})
```

**Comment by haotian-liu** [comment]
Interesting, it might be due to the filtering process in somewhere, or simply because that the network makes less valid predictions. Please trace and see where the decrease of instances happens, and see if which one is the cause. Try `torch.index_select` in such places to see if it helps.

**Comment by sinuku** [comment]
In `yolact.py`, could these be the problem?
`torch.ones((1, 256, 69, 69))`, `torch.randn(1, 512, 69, 69).cuda()`,  `torch.randn(1, 1024, 35, 35).cuda()`.. etc
If the `max_size` is changed, it should be changed too?

**Comment by sinuku** [comment]
Resolved the issue by changing what I said.
Thanks for your supply.

**Comment by marvision-ai** [comment]
@sinuku , what was the formula you used to provide the proper numbers in the `input_sizes=[....]` for your custom widthxheight? 
I am struggling with the same issue as you. 

Thanks in advance!
