### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 87563) exited unexpectedly

### ISSUE THREAD

**Issue by VbsmRobotic** [haotian-liu/yolact_edge#73]
Hi,
When I try to train model 
$ python3 train.py  --config=yolact_edge_config --resume=weights/yolact_edge_vid_resnet50_847_50000.pth 

I face the below issue :

-   File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
-     _error_if_any_worker_fails()
-  RuntimeError: DataLoader worker (pid 88428) is killed by signal: Killed. 
- The above exception was the direct cause of the following exception:
- Traceback (most recent call last):
-    File "train.py", line 707, in <module>
-      train(0, args=args)
-    File "train.py", line 357, in train
-      datum = next(data_loader_iter)
-    File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
-      data = self._next_data()
-    File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
-      idx, data = self._get_data()
-    File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
-      success, data = self._try_get_data()
-    File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
-      raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
-   RuntimeError: DataLoader worker (pid(s) 88428) exited unexpectedly

Is there any advice ?

**Comment by haotian-liu** [comment]
What device you are working on? This might be due to a OOM issue. What is the RAM size of your device?

**Comment by VbsmRobotic** [comment]
> What device you are working on? This might be due to a OOM issue. What is the RAM size of your device?
Ubuntu 20.04, 

-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    On   | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P8     8W /  N/A |   3426MiB /  5934MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1061      G   /usr/lib/xorg/Xorg                 70MiB |
|    0   N/A  N/A      1700      G   /usr/lib/xorg/Xorg                402MiB |
|    0   N/A  N/A      1873      G   /usr/bin/gnome-shell               72MiB |
|    0   N/A  N/A      3542      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A      3751      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A      4526      G   /usr/lib/firefox/firefox            2MiB |
|    0   N/A  N/A     34235      C   python                           1353MiB |
|    0   N/A  N/A     34335      C   python                           1353MiB |
|    0   N/A  N/A     37486      G   ...gAAAAAAAAA --shared-files       54MiB |
|    0   N/A  N/A     41512      G   ...AAAAAAAAA= --shared-files       66MiB |
|    0   N/A  N/A     60355      G   mpv                                10MiB |
|    0   N/A  N/A     72431      G   ...AAAAAAAA== --shared-files       20MiB |
+-----------------------------------------------------------------------------+
I have not installed TensorRT

**Comment by haotian-liu** [comment]
Please try change `num_workers` in [here](https://github.com/haotian-liu/yolact_edge/blob/master/eval.py#L953) to zero to see if the error persists.

**Comment by VbsmRobotic** [comment]
> Please try change `num_workers` in [here](https://github.com/haotian-liu/yolact_edge/blob/master/eval.py#L953) to zero to see if the error persists.

face same error :
File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 91287) exited unexpectedly

**Comment by haotian-liu** [comment]
What is the full error log? Is the pid reported here the same as the main process pid?

**Comment by VbsmRobotic** [comment]
> What is the full error log? Is the pid reported here the same as the main process pid?

I have not installed TensorRT. Can I run python3 train.py  --config=yolact_edge_config --resume=weights/yolact_edge_vid_resnet50_847_50000.pth

**Comment by haotian-liu** [comment]
Wait, you showed the command that you are running evaluation in your main thread. Which command were you using?

**Comment by VbsmRobotic** [comment]
> Wait, you showed the command that you are running evaluation in your main thread. Which command were you using?

I am using python3 train.py  --config=yolact_edge_config --resume=weights/yolact_edge_vid_resnet50_847_50000.pth

**Comment by haotian-liu** [comment]
If you run with `--num_workers 0`, will the error occur?

**Comment by VbsmRobotic** [comment]
> If you run with `--num_workers 0`, will the error occur?
yes, face same error

**Comment by haotian-liu** [comment]
Please share the full error message including the command you are using.

**Comment by VbsmRobotic** [comment]
> Please share the full error message including the command you are using.

$ python3 train.py  --config=yolact_edge_config --resume=weights/yolact_edge_vid_resnet50_847_50000.pth 

File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 92070) exited unexpectedly

**Comment by haotian-liu** [comment]
You are not running with `--num_workers 0`. And please provide the **FULL** error log.

**Comment by VbsmRobotic** [comment]
> You are **NOT** running with `--num_workers 0`. And please provide the **FULL** error log.

I have modified this line of code :
            data_loader = torch.utils.data.DataLoader(eval_dataset, num_workers=0, shuffle=False,
                                                      collate_fn=collate_fn_youtube_vis_eval)

**Comment by VbsmRobotic** [comment]
> > You are **NOT** running with `--num_workers 0`. And please provide the **FULL** error log.
> 
> I have modified this line of code :
> data_loader = torch.utils.data.DataLoader(eval_dataset, num_workers=0, shuffle=False,
> collate_fn=collate_fn_youtube_vis_eval)

Error:
WARNING [03/13 09:59:07 yolact.model.load]: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/13 09:59:07 yolact.train]: Begin training!
/home/vahid/env/detectron2/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/vahid/env/detectron2/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/vahid/env/detectron2/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/vahid/env/detectron2/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
Traceback (most recent call last):
  File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 92070) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 707, in <module>
    train(0, args=args)
  File "train.py", line 357, in train
    datum = next(data_loader_iter)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/home/vahid/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e

**Comment by haotian-liu** [comment]
It is the dataloader in the train.py causes the problem. Please run with `--num_workers 0`.

**Comment by VbsmRobotic** [comment]
> --num_workers
parser.add_argument('--num_workers', default=4, type=int,
                    help='Number of workers used in dataloading')
default =0   May I know is it correct ?

**Comment by haotian-liu** [comment]
Just put this into the command line and run. There is no need and is improper to modify the code in this way.

**Comment by VbsmRobotic** [comment]
> > --num_workers
> > parser.add_argument('--num_workers', default=4, type=int,
> > help='Number of workers used in dataloading')
> > default =0   May I know is it correct ?
Error:
WARNING [03/13 10:11:29 yolact.model.load]: Some parameters in the checkpoint have a different shape in the current model, and are initialized as they should be: prediction_layers.0.conf_layer.weight, prediction_layers.0.conf_layer.bias, semantic_seg_conv.weight, semantic_seg_conv.bias
[03/13 10:11:29 yolact.train]: Begin training!
/home/vahid/env/detectron2/yolact_edge/utils/augmentations.py:414: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
Traceback (most recent call last):
  File "train.py", line 707, in <module>
    train(0, args=args)
  File "train.py", line 431, in train
    net_outs = net(images,extras=extras)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vahid/env/detectron2/yolact_edge/yolact.py", line 1623, in forward
    outs = self.backbone(x)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vahid/env/detectron2/yolact_edge/backbone.py", line 128, in forward
    x = layer(x)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vahid/env/detectron2/yolact_edge/backbone.py", line 39, in forward
    out = self.conv3(out)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/vahid/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 5.80 GiB total capacity; 1.39 GiB already allocated; 180.75 MiB free; 1.40 GiB reserved in total by PyTorch)

**Comment by haotian-liu** [comment]
This suggests two issues:

(1) You do not have enough CPU memory to use 4 workers (which is the default, reduce it to a maximum number that fits your memory).
(2) You do not have enough GPU memory, try reducing the batch size with `--batch_size`.

**Comment by VbsmRobotic** [comment]
> This suggests two issues:
> 
> (1) You do not have enough CPU memory to use 4 workers (which is the default, reduce it to a maximum number that fits your memory).
> (2) You do not have enough GPU memory, try reducing the batch size with `--batch_size`.

Noted. Thank you for your assistance. I am trying to fix it.

**Comment by VbsmRobotic** [comment]
$ python3 train.py  --config=yolact_edge_config --resume=weights/yolact_edge_vid_resnet50_847_50000.pth --batch_size=1 --num_workers=0
get warning 
[03/13 16:48:37 yolact.train]: eta: 7 days, 7:12:00  epoch: 1  iter: 180  B: 24433224102800695609153413971968.000  M: 7.985  C: 3407748727693212651985389486080.000  S: -0.241  T: 27840972830493906009338989772800.000  time: 0.798  data_time: 0.868  lr: 0.000424  max_mem: 1851M
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan
Warning: Moving average ignored a value of inf
Warning: Moving average ignored a value of nan

**Comment by haotian-liu** [comment]
You need to adjust the learning rate and freeze the batch norm if the batch size is less than 8.

**Comment by evan-tan** [comment]
Hi there, if the batch size is 2, what should the learning rate be? Also how does one freeze the batch norm?

**Comment by reconciliation777** [comment]
> This suggests two issues:
> 
> (1) You do not have enough CPU memory to use 4 workers (which is the default, reduce it to a maximum number that fits your memory). (2) You do not have enough GPU memory, try reducing the batch size with `--batch_size`.

Excuse me. How can I set the num_workers=0 in dataloader.py?
