### ISSUE TITLE
FPS Performance was not as good as the original source on Nvidia RTX 3060

### ISSUE THREAD

**Issue by winter2897** [haotian-liu/yolact_edge#76]
Hi @haotian-liu !
Thanks for you project!
I am try to eval.py on `RTX 3060` with `CUDA : 11.1`, `cuDNN: 8.0.5`, `TensorRT: 7.2.3.4`, `torch2trt: 0.2.0` and `Pytorch: 1.8.0`. I was able to run the project but the performance was not as good as the original source, only `8FPS`. Below is the run command. Can you help me know why? 
![Screenshot from 2021-03-16 15-08-45](https://user-images.githubusercontent.com/22476495/111277486-152faa00-866b-11eb-9e74-dd7a61bab978.png)

```
python eval.py --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size 2 --video=my_video.mp4 --yolact_transfer --disable_tensorrt

```

**Comment by winter2897** [comment]
**Update**
If I run this command, I get `30fps`. I think the error lies in not installing the correct versions as you suggested. However, the `RTX 3060` card only supports higher versions of CUDA and Pytorch library packages.
```
python eval.py --trained_model=weights/yolact_edge_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size 2 --video=my_video.mp4 --yolact_transfer --use_fp16_tensorrt
```

**Comment by haotian-liu** [comment]
In the first command, you disabled the TensorRT, thus the speed is slower. What is the video resolution? If you change the video resolution to 640x360 (or something similar), what is the FPS?

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
