### ISSUE TITLE
Youtube-VIS Annotations

### ISSUE THREAD

**Issue by cyrilzakka** [haotian-liu/yolact_edge#77]
I have a dataset of images in the COCO data format that are essentially sequential frames of a video. Can that dataset be used for training the warp flow module? As far as I can tell, the Youtube-VIS dataset is the same format as COCO. Is that correct? Is there anything else I should know before training for video?

**Comment by haotian-liu** [comment]
Theoretically, yes. You can follow the description on Youtube-VIS dataset and create your own annotation.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
