### ISSUE TITLE
Coco format problem created from CVAT

### ISSUE THREAD

**Issue by MiaoRain** [haotian-liu/yolact_edge#78]
Hello
when use Labelme to create the COCO dataset, everything goes well. However, when use CVAT to create the COCO dataset, here is the problem. 
![image](https://user-images.githubusercontent.com/47746159/112142111-22bbd580-8c11-11eb-832a-cc764ee7b0f9.png)

How to deal with this?

**Comment by MiaoRain** [comment]
Solved, Thanks！

**Comment by haotian-liu** [comment]
Glad you have your problem solved!

**Comment by hamedmh** [comment]
Hi @MiaoRain ,
I need to create a new dataset to use it for segmentation of objects in still images.
Should I export the dataset using COCO 1.0 in CVAT, or another format?
Where should I put the different files so that yolact_edge can find and use them?
Thanks!
Best regards,
Hamed
