### ISSUE TITLE
from pycocotools.ytvos import YTVOS

### ISSUE THREAD

**Issue by zihan987** [haotian-liu/yolact_edge#8]
from pycocotools.ytvos import YTVOS这块一直报错，提示没有

**Comment by haotian-liu** [comment]
Just updated [INSTALL.md](INSTALL.md). Please install pycocotools with YTVOS support: `pip install git+https://github.com/haotian-liu/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"`

**Comment by zihan987** [comment]
谢谢

**Comment by TaylorLi123** [comment]
> 刚刚更新 [INSTALL.md](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md)。请安装支持 YTVOS 的 pycocotools：`pip install git+https://github.com/haotian-liu/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"`

您好，我在按照时报错：note: This error originates from a subprocess, and is likely not a problem with pip.请问应该如何解决谢谢
