### ISSUE TITLE
C++ inference for AGX Xavier

### ISSUE THREAD

**Issue by zwyzwy** [haotian-liu/yolact_edge#81]
The paper seems to inference the model by python code in real time?
Shall we take a c++ code to inference the model to achieve faster inference?

**Comment by zwyzwy** [comment]
Can you give some c++ inference example code? I cant find how to get the trt engine and post processing? 
Many thanks !

**Comment by haotian-liu** [comment]
Sorry, currently we only have the implementation in Python.

**Comment by MiaoRain** [comment]
> Sorry, currently we only have the implementation in Python.

Hi, where is python inference code? Thanks a lot.
