### ISSUE TITLE
NameError: name 'torch2trt' is not defined

### ISSUE THREAD

**Issue by batselem** [haotian-liu/yolact_edge#84]
Thank you for sharing your wonderful work. 

I got the following error in colab notebook you have provided.

`NameError: name 'torch2trt' is not defined`

Thanks

**Comment by haotian-liu** [comment]
torch2trt is not configured successfully. Please check previous blocks to verify the configuration for both TensorRT and torch2trt.

**Comment by batselem** [comment]
Okay I will try it. I have tested the notebook without trt, the inference time is 0.26 seconds. Is it accurate?
