### ISSUE TITLE
Low fps result

### ISSUE THREAD

**Issue by batselem** [haotian-liu/yolact_edge#85]
The paper reports that without tensorrrt it obtains 67.0fps and with tensorrt it obtains on RTX 2080 Ti. But I have tested the notebook without trt, the inference time is 0.26 seconds. I have checked Colab GPU and it was Tesla T4. I wonder why it performs so poorly.

**Comment by haotian-liu** [comment]
How did you measure the FPS? Did you use the `--benchmark` option?

**Comment by batselem** [comment]
Thank you for your quick response.

I measured the runtime in the colab notebook as follows:
```
start_time = time.time()
with torch.no_grad():
    preds = net(batch, extras=extras)["pred_outs"]
end_time = time.time()
runtime = end_time - start_time

print("--- %s seconds ---" % runtime)  
```

**Comment by haotian-liu** [comment]
Please run the network forwarding op for multiple times (e.g. 100/1000), and average the runs.

**Comment by batselem** [comment]
I am sorry. you are right. I tested it with 1000 steps and computed the average value. As result, the runtime was 55seconds and the speed was 17fps on Tesla T4 (Colab).

**Comment by haotian-liu** [comment]
Glad that you have the doubts clarified :)
