### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by Tetsujinfr** [haotian-liu/yolact_edge#87]
hi
I got the below error, not sure why it is happening. All the model steps have passed but somehow right after accessing th camera it seems that the image frame is not at the expected format.

> python3 eval.py --trained_model=weights/yolact_edge_mobilenetv2_54_800000.pth --score_threshold=0.3 --top_k=100 --video_multiframe=2 --trt_batch_size 2 --video=0 --use_fp16_tensorrt
> Config not specified. Parsed yolact_edge_mobilenetv2_config from the file name.
> 
> [04/02 01:10:07 yolact.eval]: Loading model...
> [04/02 01:10:14 yolact.eval]: Model loaded.
> [04/02 01:10:14 yolact.eval]: Converting to TensorRT...
> [04/02 01:10:14 yolact.eval]: Converting backbone to TensorRT...
> [04/02 01:10:16 yolact.eval]: Converting protonet to TensorRT...
> [04/02 01:10:16 yolact.eval]: Converting FPN to TensorRT...
> [04/02 01:10:16 yolact.eval]: Converting PredictionModule to TensorRT...
> [04/02 01:10:35 yolact.eval]: Converted to TensorRT.
> [ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
> [TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0
> Initializing model... Traceback (most recent call last):
>   File "eval.py", line 1281, in <module>
>     evaluate(net, dataset)
>   File "eval.py", line 928, in evaluate
>     evalvideo(net, args.video)
>   File "eval.py", line 769, in evalvideo
>     eval_network(transform_frame(get_next_frame(vid)))
>   File "eval.py", line 702, in eval_network
>     net_outs = net(imgs, extras=extras)
>   File "/home/tetsfr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/tetsfr/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/tetsfr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/media/tetsfr/SSD/yolact_edge/yolact.py", line 1738, in forward
>     proto_out = proto_out.permute(0, 2, 3, 1).contiguous()
> RuntimeError: number of dims don't match in permute
> Segmentation fault

I have tested my camera and it works well. In eval.py I think the `get_next_frame(vid)` function return the pair of images as expected, the `transform_frame(frames)` converts into a cuda tensor if I understand correctly, so I do not see an issue here.
But at the end of the day the format of the input tensor is not as expected by the model, not sure why.

Does anyone know what I need to do to fix this?
thanks a lot

**Comment by haotian-liu** [comment]
Can you try [safe mode](https://github.com/haotian-liu/yolact_edge#handling-inference-error-when-using-tensorrt)?

**Comment by Tetsujinfr** [comment]
I tried to run it with the safe mode again from scratch but that still fails.
Here is the log of the conversion steps (there are some warnings, not sure if expected):

> [04/02 02:19:56 yolact.eval]: Loading model...
> [04/02 02:20:04 yolact.eval]: Model loaded.
> [04/02 02:20:04 yolact.eval]: Converting to TensorRT...
> WARNING [04/02 02:20:04 yolact.eval]: Running TensorRT in safe mode. This is an attempt to solve various TensorRT engine errors.
> [04/02 02:20:04 yolact.eval]: Converting backbone to TensorRT...
> [04/02 02:21:06 yolact.eval]: Converting protonet to TensorRT...
> Warning: Encountered known unsupported method torch.nn.functional.interpolate
> [04/02 02:21:10 yolact.eval]: Converting FPN to TensorRT...
> Warning: Encountered known unsupported method torch.zeros
> Warning: Encountered known unsupported method torch.nn.functional.interpolate
> Warning: Encountered known unsupported method torch.nn.functional.interpolate
> [04/02 02:21:28 yolact.eval]: Converting PredictionModule to TensorRT...
> [04/02 02:21:44 yolact.eval]: Converted to TensorRT.
> [ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
> Initializing model... 
> [TensorRT] ERROR: INVALID_ARGUMENT: Cannot find binding of given name: input_0
> Traceback (most recent call last):
>   File "eval.py", line 1284, in <module>
>     evaluate(net, dataset)
>   File "eval.py", line 931, in evaluate
>     evalvideo(net, args.video)
>   File "eval.py", line 772, in evalvideo
>     eval_network(transform_frame(get_next_frame(vid)))
>   File "eval.py", line 703, in eval_network
>     net_outs = net(imgs, extras=extras)
>   File "/home/tetsfr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/tetsfr/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/tetsfr/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/media/tetsfr/SSD/yolact_edge/yolact.py", line 1738, in forward
>     proto_out = proto_out.permute(0, 2, 3, 1).contiguous()
> RuntimeError: number of dims don't match in permute
> Segmentation fault

Still getting the same error. Do I need to do something special for the models prep, or regarding the config specification?

**Comment by haotian-liu** [comment]
```
Warning: Encountered known unsupported method torch.nn.functional.interpolate
Warning: Encountered known unsupported method torch.nn.functional.interpolate
```

It seems that `torch2trt` is not [installed](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md) correctly.

**Comment by Tetsujinfr** [comment]
I did re-install torch2trt, no error at install time, but I still have the same issues. I saw this, so maybe there are some intricate compilation details I need to try.

Is it possible for you to share the pre-trained models converted for trt on AGX though? I would expect them to run as is on NX.

**Comment by haotian-liu** [comment]
Please try running [benchmark](https://github.com/haotian-liu/yolact_edge#benchmarking) to see if it is a environment issue. Unfortunately, sharing `.trt` cache won't let you run on your device because it is environment-dependent.

**Comment by Tetsujinfr** [comment]
The benchmarking did not finish , I had a segmentation fault (details below). Usually that indicate not enough memory type^of issues, and it happened when I had 7.2GB out of 7.8GB used. Note that I have a 32GB swap file on a fast nvme key but I suspect that is not used by the torch implementation.
python3 eval.py --trained_model=weights/yolact_edge_54_800000.pth --benchmark --max_images=500
Config not specified. Parsed yolact_edge_config from the file name.
> loading annotations into memory...
> Done (t=1.48s)
> creating index...
> index created!
> [04/04 02:27:22 yolact.eval]: Loading model...
> [04/04 02:27:42 yolact.eval]: Model loaded.
> [04/04 02:27:42 yolact.eval]: Converting to TensorRT...
> [04/04 02:29:00 yolact.eval]: Converting backbone to TensorRT...
> Traceback (most recent call last):
>   File "eval.py", line 1279, in <module>
>     convert_to_tensorrt(net, cfg, args, transform=BaseTransform())
>   File "/media/tetsfr/SSD/yolact_edge/utils/tensorrt.py", line 156, in convert_to_tensorrt
>     net.to_tensorrt_backbone(cfg.torch2trt_backbone_int8, calibration_dataset=calibration_dataset, batch_size=args.trt_batch_size)
>   File "/media/tetsfr/SSD/yolact_edge/yolact.py", line 1501, in to_tensorrt_backbone
>     self.trt_load_if("backbone", trt_fn, [x], int8_mode, batch_size=batch_size)
>   File "/media/tetsfr/SSD/yolact_edge/yolact.py", line 1483, in trt_load_if
>     module = trt_fn(module, trt_fn_params)
>   File "/usr/local/lib/python3.6/dist-packages/torch2trt/torch2trt.py", line 399, in torch2trt
>     engine = builder.build_cuda_engine(network)
> RuntimeError: Method: read_calibration_cache was not overriden. Please provide an implementation for this method.
> Segmentation fault

Can you share what is the peak memory usage on your AGX board when you run the benchmarking ?

This way I would know if I can have a chance by optimising the NX memory usage (I can get more 1GB eventually but no more and I am trying not to go down this route)
Btw I think the initial issue I had was not memory related but happy to go the benchmarking way and go through the motion to dble check.

thanks

**Comment by haotian-liu** [comment]
It seems that your cache was corrupted. Please remove all the cache (files with extension `.trt` in the folder where your model is stored.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.

**Comment by Tetsujinfr** [comment]
I did try removing all .trt cache files but the result was the same. I suspect the Jetson NX does not have enough memory to infer the model, or there is another issue somehow.
If someone gets it to work on NX please give a shout.
But it does not work for me so far. Thanks for the repo and your help on trying to resolve this anyway, but Yolact edge not just yet working on <2kg edge devices.

**Comment by haotian-liu** [comment]
YolactEdge works on NX as https://github.com/haotian-liu/yolact_edge/issues/45. You could try reducing the calibration set.

**Comment by DrZ-21** [comment]
Dude, I met the same problem as yours. I changed the parameter 'torch2trt_max_calibration_images' to 1 and it worked.
