### ISSUE TITLE
running this on Jetson xavier NX

### ISSUE THREAD

**Issue by Tetsujinfr** [haotian-liu/yolact_edge#88]
hi 

thanks for the great repo.

I am trying to run this on the Jetson Xavier NX, did anyone do it and if yes were there difficulties on the way?
I think there is not enough memory on the device to complete the image calibration step for the int8 trt inference. It systematically crashes on my end (segmentation fault).

Also, when trying to run the fp16 trt version of the webcam demo, right before starting the image inference, the memory consumed is about 3.3GB. I know that segmentation is not cheap but that is quite a sizeable malloc.

Trying to run this on an edge device, any feedback is welcomed. thanks.

**Comment by haotian-liu** [comment]
For image calibration, you can use a smaller set of calib-image: `cfg. torch2trt_max_calibration_images = 5`.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
