### ISSUE TITLE
HI Bro i have a new problm about your new version????????

### ISSUE THREAD

**Issue by a-chance888** [haotian-liu/yolact_edge#90]
Hello, when you released the first version last December, I was able to use your code successfully, but now after you update, I have some errors. When I run eval.py, I get an error RuntimeError: stack expects a non-empty TensorList. Can you give me some suggestions for correction? thank you very much for your help.

**Comment by haotian-liu** [comment]
Please share the command you are using and paste the full log here.

**Comment by a-chance888** [comment]
No log file is generated, my configuration environment is as follows:
python=3.6
pytorch=1.6
cuda=10.2
cudnn=8.0
tensort=7.1.3.4

**Comment by a-chance888** [comment]
- [ ] 

> 
![2021-04-03 18-18-40屏幕截图](https://user-images.githubusercontent.com/65146982/113496622-219e7880-952e-11eb-85e6-95224477d094.png)

**Comment by a-chance888** [comment]
png, jpg, and jpeg formats are all like this.

**Comment by haotian-liu** [comment]
Please download calibration dataset as instructed [here](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md).

**Comment by a-chance888** [comment]
ok,i will try ,thank you!!!

**Comment by a-chance888** [comment]
Hello, author, according to your guidance, my previous error has been solved, but now I have a new problem, can you give me some valuable advice again? thank you very much.
![3](https://user-images.githubusercontent.com/65146982/113499168-7352fd00-9546-11eb-9bf5-018046c8868c.png)

**Comment by haotian-liu** [comment]
Answered in #91.
