### ISSUE TITLE
UnboundLocalError: local variable 'detections' referenced before assignment

### ISSUE THREAD

**Issue by a-chance888** [haotian-liu/yolact_edge#91]
Hello, author, according to your guidance, my previous error has been solved, but now I have a new problem, can you give me some valuable advice again? thank you very much.
![3](https://user-images.githubusercontent.com/65146982/113499302-7bf80300-9547-11eb-8ee3-8a955febf006.png)

**Comment by haotian-liu** [comment]
Hi, there was an error introduced in one of our newest commits, and I just committed the fix. Please pull the commit and try again, thanks.
