### ISSUE TITLE
out of box

### ISSUE THREAD

**Issue by mathmax12** [haotian-liu/yolact_edge#93]
![image](https://user-images.githubusercontent.com/32367611/113535494-6eaf3880-9588-11eb-9476-c467d8734bfe.png)

In some cases, I saw part of my body is out of the boundary.
What may cause this issue?

**Comment by haotian-liu** [comment]
It was because the bounding box prediction is not perfect -- it crops the masks. For details of how masks are generated, please refer to our paper. Thanks.

**Comment by mathmax12** [comment]
Thanks for that.
I wonder is this cropping happens from the post-processing stage (i.e, merge bounding box and mask after the generation of these two) or it from the inference part of the network.
If we don't need the bounding box and just interested in the mask, is there something we can do to avoid this cropping  on the current pretrained network?

**Comment by haotian-liu** [comment]
It is done in the post-processing stage. You could disable that, but it will cause more issues including `leakage`. You could refer to [our paper](https://arxiv.org/abs/2012.12259) and [YOLACT](https://arxiv.org/abs/1904.02689) for more explanations.

**Comment by mathmax12** [comment]
Thanks.
