### ISSUE TITLE
Is a new bug??????

### ISSUE THREAD

**Issue by a-chance888** [haotian-liu/yolact_edge#94]
![88](https://user-images.githubusercontent.com/65146982/113543392-e036c780-9618-11eb-8817-ea56100cc39a.png)
What should I do to solve this problem?

**Comment by haotian-liu** [comment]
Please follow the instructions [here](https://github.com/haotian-liu/yolact_edge/blob/master/INSTALL.md) to organize the dataset, and follow the instructions [here](https://github.com/haotian-liu/yolact_edge#evaluation) on the command to run evaluation.
