### ISSUE TITLE
IndexError when evaluating custom trained set with TensorRT

### ISSUE THREAD

**Issue by ngeerlingsriwo** [haotian-liu/yolact_edge#96]
I have the following situation: I have trained Yolact Edge with a custom dataset, containing only one class (+ background). When I evaluate this dataset with `--disable_tensorrt` or `--use_tensorrt_safe_mode` everything works, but when I do use TensorRT I get the following error:

```
.../yolact_edge/layers/functions/detection.py", line 212, in fast_nms
    classes = classes[keep]
IndexError: The shape of the mask [81] at index 0 does not match the shape of the indexed tensor [1, 81] at index 0.
```

I have added print statements before `classes = classes[keep]`:
```
print("\n classes : ", classes.shape)
print("\n keep : ", keep.shape)
```
For both of them the result was: `torch.Size([1, 81])`.

So I'm unsure where the problem now is: is it that Yolact Edge cannot handle custom training for only one class? Or could something have gone wrong during training? I printed the amount of classes in `cfg.num_classes` when starting the training and that was 2. Can anyone help me out?

**Comment by haotian-liu** [comment]
Hi in "When I evaluate this dataset with `--disable_tensorrt` **or** `--use_tensorrt_safe_mode` everything works", do you mean **and** or **or**? If `--use_tensorrt_safe_mode` works for you, just use that as it is exactly using TensorRT.

**Comment by ngeerlingsriwo** [comment]
Thank you for your quick response! 

I meant 'or' for the arguments.

I thought that the optimal way to run Yolact Edge was without the `--use_tensorrt_safe_mode`, but if I understand correctly from you comment this does not influence the speed. Why is TensorRT not used in safe mode by default?

**Comment by haotian-liu** [comment]
I do not see an obvious FPS drop after several iterations/optimizations of the code, but theoretically it might be slightly slower and might have some side effects. I plan to make it default some time later, but still make it remain an optional argument for now. Sorry for the confusion.

**Comment by a-chance888** [comment]
Hi,bro！ i have same problem? Do you have other ways to solve this problem?
