### ISSUE TITLE
The Flop about whole model 

### ISSUE THREAD

**Issue by ntut108318099** [haotian-liu/yolact_edge#97]
Hi , Sorry to bother you again.

As the issue title said , I want to know the flops parameter about whole model.
Where can I find it ? Is it possible to know the parameters ?

Are the flops  just like as the max_mem in the training log ?

Thanks for your reading~
Have a nice day.

**Comment by haotian-liu** [comment]
This might be a helpful tool (not sure if this is the one I was using some time before): https://github.com/1adrianb/pytorch-estimate-flops

**Comment by ntut108318099** [comment]
> This might be a helpful tool (not sure if this is the one I was using some time before): https://github.com/1adrianb/pytorch-estimate-flops

Thanks for your reply, I will try it . I could share the result if you want to add on your "Readme.md" .

BTW, I found your mobilenetv2 pretrined model came from pytorch-torchvision model. 
The pretrained_model was trained with 224*224 image, and  your config file used  550*550 to train yolact_edge . 
Is it possible to increase the final mAP with 224*224 image ?

**Comment by haotian-liu** [comment]
It won't. You could refer to YOLACT paper for some ablations. And it is common to use ImageNet-pretrained model in object detection networks.

**Comment by haotian-liu** [comment]
I am closing this issue for now due to inactivity. If there are any further questions that I could help with, please feel free to reopen, thanks.
